### ISSUE TITLE
embedded heredoc terminator not properly checked

### ISSUE THREAD

**Issue by vapier** [koalaman/shellcheck#1050]
shellcheck.net incorrectly rejects:

```sh
#!/bin/sh
cat <<EOF
foo
EOF hi
EOF
```

you can change the ` hi` to `;` or ` ` (just a space) and shellcheck doesn't like any of them.  this is a bit of a contrived case, but it came up in two non-contrived scenarios:

* creating a heredoc of SQL code which itself used a heredoc-like syntax
```sh
#!/bin/sh
mysql-like-tool <<EOF
...some SQL...
DEFINE TABLE table1 <<EOF
  ...table logic...
EOF;
...more SQL...
EOF
```

* displaying a usage string where the heredoc delimiter happened to show up in the text at the "wrong" place
```sh
#!/bin/sh
usage() {
  cat <<EOF
...some block of text...
EOF is reached.
...more block of text...
EOF
}
```

#### Here's what shellcheck currently says:
```
Line 4:
EOF hi
   ^-- SC1122: Nothing allowed after end token. To continue a command, put it on the line with the <<.
```

**Comment by koalaman** [comment]
Agreed.

This was originally intentional because it was generally what the user seemed to expect, like this perfectly well-formed but wrong snippet:

```
cat << eof
foo
eof | nl

cat << eof
more stuff
eof
```

Misparsing a script means you can't simply ignore the issue though, so it should be fixed to flag the (potential) issue while continuing to parse correctly.

**Comment by koalaman** [comment]
This now parses correctly. The warning is still there, but it can be disabled/ignored.
