### ISSUE TITLE
Any thoughts on implementing the Language Server Protocol

### ISSUE THREAD

**Issue by mads-hartmann** [koalaman/shellcheck#1103]
Have you considered expanding the scope of shellcheck to be able to run as a server that speaks the [Language Server Protocol][lsp]. Shellcheck is in a good position to do this as it already has a proper parser.

[lsp]: https://microsoft.github.io/language-server-protocol/

**Comment by koalaman** [comment]
This is definitely falls outside the scope of ShellCheck itself.

Some tool could conceivably use the ShellCheck parser for this, and it's already exposed as a library, but it's not trivial:

* It tracks start positions but not end positions
* It has no support for partial parsing or error recovery, like when you've only written half your statement but still want insights
* It's opinionated, and will e.g. get hung up on a statement like `IF[a==b]` because it thinks the user wanted `if [ a == b ]`
* It's not very snappy for large files, since it does a lot of backtracking for some good (but mostly bad) reasons

**Comment by mads-hartmann** [comment]
@koalaman That's totally understandable, thanks for being so specific 👍
