### ISSUE TITLE
EPEL new rpm package

### ISSUE THREAD

**Issue by JAPRESSLEY** [koalaman/shellcheck#1274]
Currently the latest rpm version for EPEL7 is 0.3.5. Is it possible to add a later distro to the repository as this version is years old now

**Comment by koalaman** [comment]
Distro packaging is independently handled by wonderful volunteers on each distro.

EPEL Package maintainer Greg Hellings informs me that new versions of ShellCheck are tricky because they'd have to use the RHEL7 GHC, which is the five year old 7.6.3. This compiler is far out of date, and is additionally blocked by ShellCheck due to a compiler optimizer bug (#1131). 

You can use a precompiled, statically linked binary instead (see https://github.com/koalaman/shellcheck/#installing) , or build your own version using Stack which will download an appropriate GHC version.
