### ISSUE TITLE
Fails on `===() { :; }`

### ISSUE THREAD

**Issue by ingydotnet** [koalaman/shellcheck#1366]
#### For bugs
- SC1036
- 0.4.6
- [x] I read https://github.com/koalaman/shellcheck/wiki/SC1036
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit

#### Here's a snippet or screenshot that shows the problem:

```sh
#!/bin/bash

# These function calls and definitions are fine:
+++
===
+++() { :;}

# But this fails and stops the parser:
===() { :;}
```

#### Here's what shellcheck currently says:
```
In x line 9:
===() { :;}
   ^-- SC1036: '(' is invalid here. Did you forget to escape it?
   ^-- SC1088: Parsing stopped here. Invalid use of parentheses?
```

#### Here's what I wanted or expected to see:

This is valid Bash and I need it for a real DSL that I'm working on.

I'm using `+++`, `---`, `...` and they shellcheck fine.

Also `===` shellchecks fines as a function *call* but just not for a function definition.

**Comment by koalaman** [comment]
You're right of course. You can work around this limitation with the `function` keyword:

    function ===() { :;}

ShellCheck intentionally allows a wider variety of symbols in function names when using `function` (specifically `[]*=!`).

This design decision was made because bash considers e.g. `if ![var=()` to be the start of a function definition, but it would be confusing and misleading for ShellCheck to talk about missing function bodies and such, and trial runs on a corpus of bad scripts supported this.

**Comment by ingydotnet** [comment]
I didn't know about the `function ` prefix workaround. This is perfect for my needs, and a great general solution. Thanks.

PS Is there a good place to read about shellcheck "workarounds" like this one?
