### ISSUE TITLE
"Internal error for --format" using gcc format

### ISSUE THREAD

**Issue by varac** [koalaman/shellcheck#1507]
#### For bugs

- My shellcheck version (`shellcheck --version` or "online"): 0.6.0 (installed with `stack intall ShellCheck`) today

#### Here's a snippet or screenshot that shows the problem:

```sh
#!/usr/bin/env sh
echo hi
```

#### Here's what shellcheck currently says:

Default format is ok:

```
$ shellcheck -s bash  /tmp/test.sh
$
```

But using gcc produces this error:

```
$ shellcheck -s bash -x -f gcc - < /tmp/test.sh
Internal error for --format. Please file a bug :(

$ shellcheck -s bash -f gcc /tmp/test.sh 
Internal error for --format. Please file a bug :(
```

**Comment by varac** [comment]
Damn, my fault.

**Comment by yjfguhd** [comment]
I am seeing this for any script, specifying any format, since a git pull from yesterday. From my reflog, I think a change since commit a621eba6d3426c5d8aa1550ffc7f0621486920f6 has caused this. I note that the expected output (ie, that showing errors and such from the script being scrutinised) is still produced. It is just always preceded by the "Internal error" line, as shown in the original report. I'm using GHC 8.0.2.

**Comment by koalaman** [comment]
Oh, so that's what that seemingly useless default branch was for. Thanks!
