### ISSUE TITLE
Feature request: bash pitfall: local will overwrite $?

### ISSUE THREAD

**Issue by pihentagy** [koalaman/shellcheck#151]
Shellcheck should warn, if you try to use $? followed by a local assignment.

```
#!/bin/bash

fu() {
  local res=$(false)
  exit $? # will return 0
}

print "$(fu)"
```

**Comment by koalaman** [comment]
This was fixed at some earlier point with SC2155. 

The exception is `readonly`, because you can't `readonly` a variable and then assign it.

**Comment by egor-tensin** [comment]
@koalaman I would like to return to your last comment. I don't think `readonly` should be an exception, because you can in fact assign to a variable, and *then* mark it as `readonly`. Both of these would work:

```
readonly x="$( false )"
```

```
x="$( false )"
readonly x
```

but the exit code of `false` is masked by `readonly` in the first example. Therefore I think that it should work the same way it does for `local`s, only that the `readonly` statement should follow the assignment and not precede it.

I'm not sure this is a proper place to raise this concern; I'll open an issue if I notice this isn't addressed for a long time.
