### ISSUE TITLE
Useless cd notice and no warning for options to echo?

### ISSUE THREAD

**Issue by fniessen** [koalaman/shellcheck#1542]
Dear Koalaman,

This is the best finding I've done on the Internet for a looong time now; impressed by this.

Just checking this script on your online page:

    #!/usr/bin/env bash
    Usage ()
    {
        cat << EOF 1>&2
    Usage: $CMD FILE
    EOF
        exit 2
    }

    # Command name.
    CMD=$(basename "$0")

    if [ $# -ne 1 ]; then
        Usage
    fi

    # Get basename of file.
    FILE="${1##*/}"

    get_references() {
        grep -F -l --include=*.{axvw,js,java} -r "$1" . | grep -v "$3" | while read -r subfile; do
            # Read each line of the grep result into the variable subfile.
            subfile="$(basename "$subfile")"
            echo -e -n "$2"
            color_file_ext "$subfile"
            echo -e "\t" "[34m" "$(afm-tasks "$subfile" 2> /dev/null | cut -d$'\t' -f2)" "[0m"
            get_references "$subfile" '    '"$2" "$3"'\|'"$subfile"
        done
    }

    function color_file_ext {
        extension="${1##*.}"
        case $extension in
            "axvw") echo -e -n "[33m$1[0m";;
            "js")   echo -e -n "[32m$1[0m";;
            "java") echo -e -n "[31m$1[0m";;
            *)     echo -e -n "$1";
        esac
    }

    # Main.
    ( git rev-parse && cd "$(git rev-parse --show-toplevel)" ;
    while test $# -gt 0; do
        # Loop so more than one file can be given as argument to this script.
        echo "File Dependency Tree View for file:"
        color_file_ext "$FILE"
        echo -e "\t" "[34m" "$(afm-tasks "$FILE" 2> /dev/null | cut -d$'\t' -f2)" "[0m"
        get_references "$FILE" '|__ ' "$FILE"
        shift
    done )

returns me a trouble for the `cd` (first line of "Main").  Though, I don't think I need fixing it: either the `cd` is successful, or it simply stays where it is, and goes on with the rest of the script.

Other notice: I'm surprised to have no warning for the `echo -e -n` while I did have such in other scripts I've run through your site.

Once again, thanks a lot for this wonderful work!  It really is something meaningful, and very useful...

**Comment by koalaman** [comment]
I'm glad you're finding it useful!

It's rare not to care which directory you're in after a `cd`. You've clearly thought it through though, so it's fine. When you know something ShellCheck doesn't, you should feel free to ignore the issue with [a directive](https://github.com/koalaman/shellcheck/wiki/Directive) or similar.

In this case you can also rewrite it to show your intent to ShellCheck and other humans using `cd ... || true`, the same way you otherwise ignore failures in certain commands in exit status and `set -e`:

```
if git rev-parse
then
  # Try to go to the top-level git directory, but don't care
  # if it fails because then we'll fall back on the current directory
  cd "$(git rev-parse --show-toplevel)" || true
fi
```

The reason why you only occasionally get warnings for `echo` flags is probably the shebang. You don't get warnings in a Bash script, because Bash always supports flags for echo:

```
#!/bin/bash
echo -e -n "hello world"  # No warning, supported in bash
echo ...
```

However, you do get them in `sh` scripts:

```
#!/bin/sh
echo -e -n "hello world"  # Warning, not always supported by sh
echo ...
```

The bash script would run the same on all platforms, whereas the `sh` script may behave differently. Here's the output of the `sh` script on Debian Linux whose `sh` doesn't support `-e`:

```
debian$ ./myscript
-e -n hello world
...
```

and here's the output on macOS whose `sh` is actually Bash:

```
hello world...
```

Hope that answers your questions.

**Comment by fniessen** [comment]
Dear @koalaman ,

This answer is more than what I expected!

Thanks a lot for this clear, explicit and complete explanation…  Very useful…

Best regards,
Fabrice

**Comment by fniessen** [comment]
Dear @koalaman ,

Got another thinking about this, and I do think you're right -- the cd should succeed, otherwise it's a big problem (permission or something like that). So, yes, I should fail in that case. Thanks!

A quick question:
- What's your standpoint regarding [[ … ]] vs [ … ]?
- What's your standpoint regarding echo vs printf?  Would you choose for printf so that it's more easy to convert to sh or dash?

(Using Cygwin Bash BTW -- any advice is welcome!)

**Comment by koalaman** [comment]
I don't have any particularly strong opinions on either, since they both have their place. 

I would lean towards `[[` when writing Bash/Ksh, if only because it additionally supports glob, extglob and regex matching. The downside is that it may [execute arbitrary code](https://www.vidarholen.net/contents/blog/?p=716) when comparing integers. 

I don't consider less strict quoting or the ability to do `&&/||` with canonical precedence a particular benefit myself, but I know other people appreciate that.

As for `echo`/`printf`, I would definitely use `printf` if I needed specific format options like padding, or to ensure that a string is exactly the way I want it, especially across shells.

Otherwise, `echo` is quick and simple, and while no one ever localizes their messages, `echo $"..."` is better than `printf $"..." ..` since translators can change the parameter order to fit the language.

So I would say tl;dr: Be aware of the differences and use whatever makes sense in that context
