### ISSUE TITLE
Add support for stdin

### ISSUE THREAD

**Issue by ad-si** [koalaman/shellcheck#1586]
Shellcheck should add support for stdin.

- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's what shellcheck currently says:

```bash
$ cat test.sh | shellcheck
No files specified.
```

#### Here's what I wanted or expected to see:

Basically the same as:

```bash
$ shellcheck <(cat test.sh)
```

**Comment by mineo** [comment]
It's not explicitly stated in the documentation AFAIK, but `shellcheck -` reads from stdin.

**Comment by ad-si** [comment]
Yes, seems to work. Thx. This should definitely be added to the documentation 😳

**Comment by ad-si** [comment]
But actually it should also work without the dash!?

**Comment by koalaman** [comment]
The man page now mentions this. Also note that this is not a ShellCheck convention, but can be expected to work on basically all Unix commands.

Since ShellCheck is intended to check script files and to help confused newbies, it's probably better that running `shellcheck` without arguments gives a `--help` type summary rather than appearing to hang waiting for stdin.

**Comment by TinCanTech** [comment]
newbies ..

shellcheck .. breaking the _mold_

**Comment by ad-si** [comment]
@koalaman But you can have both! E.g. in JavaScript if you have a file `test.js`:

```js
#! /usr/bin/env node

if (process.stdin.isTTY) {
  console.log('Help text prints to terminal')
}
else {
  console.log('Prints to stdout')
}
```

```txt
$ ./test.js
Help text prints to terminal

$ cat file.sh | ./test.js
Prints to stdout
```

This should also be possible in Haskell, right?
