### ISSUE TITLE
SC2140

### ISSUE THREAD

**Issue by michaelsstuff** [koalaman/shellcheck#1589]
Hi,

this is for SC2140
I am not perfectly sure if this is a bug or not, but want to mention it. shellcheck does have an issue with the following:

#### The code:
```
eval steamu="$"STEAMUSER"$i"
```

$i is a number here.
In bash it works fine and creates me a new variable.

e.g.: $STEAMUSER5

#### Here's what shellcheck currently says:
```
^-- SC2140: Word is of the form "A"B"C" (B indicated). Did you mean "ABC" or "A\"B\"C"?
```

Also the source of the script:
https://github.com/michaelsstuff/arma3-for-hcloud/blob/master/blah.sh

Cheers
Michael

**Comment by koalaman** [comment]
This is an interesting case because the quotes in `"STEAMUSER"` actually do serve a purpose, even if it's a strange one: they're positioned to split up the `$` and following characters so the `$` will be literal as well. This is more commonly done by escaping or using single quotes.

ShellCheck's intention was to suggest e.g. `eval steamu="\$STEAMUSER$i" where quotes are used for more canonical purposes.

544047c5afa adds [SC1135](https://github.com/koalaman/shellcheck/wiki/SC1135) to suggest using backslash instead of ending the quote, which makes the SC2140 more reasonable.

Thanks!
