### ISSUE TITLE
Package version very old on Ubuntu Disco Dingo repo

### ISSUE THREAD

**Issue by stderr-to-devnull** [koalaman/shellcheck#1699]
Available version is 0.5.0

**Comment by koalaman** [comment]
That is indeed frustrating, and also somewhat outside of my control. Consider installing the [Snap package](https://snapcraft.io/shellcheck) instead, since I maintain that and keep it up to date on every release. Ubuntu integrates Snap so this should be quick and straight forward.

Alternatively, you can file a bug with Ubuntu or drop in a binary release.

**Comment by stderr-to-devnull** [comment]
Thanks for the reply. I will use snap.
