### ISSUE TITLE
/usr/bin/shellcheck gigantic

### ISSUE THREAD

**Issue by jidanni** [koalaman/shellcheck#1715]
I notice the binary is **14 megabytes big** here on Debian. Something must be wrong.

**Comment by koalaman** [comment]
The [official binary releases](https://shellcheck.storage.googleapis.com/index.html) are currently 7.5MiB for x86_64, so you can consider installing those instead.

That's still pretty chunky of course, and the reason for this is that it (like Debian's) bundles all relevant parts of the Haskell runtime and library dependencies so you don't need to install those separately. This makes sense because chances are that ShellCheck is the only Haskell tool on the system, so there's nothing else over which to amortize the cost of a generic runtime. 

This is not unlike Python, where each script would be 20MB if they couldn't take for granted that everyone already has a Python runtime installed.

(If you'd want Debian to ship binaries closer to 7.5MiB instead of 14MiB, you'd have to file an issue with them. Distro packaging is handled by different, wonderful volunteers, and not by ShellCheck itself).

**Comment by jidanni** [comment]
Much bigger than e.g.,
$ which bash|xargs du -h
1.2M    /bin/bash

OK, I filed
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=941717
