### ISSUE TITLE
alpine image does not behave like "regular"

### ISSUE THREAD

**Issue by BeyondEvil** [koalaman/shellcheck#1720]
With the regular image I simply do:

`docker run --rm -v "$PWD:/mnt:ro" koalaman/shellcheck:stable *.sh`

But with the alpine version I have to be more explicit:

`docker run --rm -v "$PWD:/mnt:ro" -w /mnt --entrypoint /bin/shellcheck koalaman/shellcheck-alpine:stable *.sh`

Is that by design?

If so, why? (just curious).

**Comment by koalaman** [comment]
Yes, this is by design.

The `shellcheck-alpine` image is exactly like `alpine` but with ShellCheck pre-installed. The entrypoint is set to `sh` and requires you to specify a full shell command (`shellcheck` or otherwise) just like any other `alpine` based image.

Meanwhile, the `shellcheck` image does not contain a shell or any other userspace utilities. The entrypoint is therefore just ShellCheck itself.

They used to work the same, but the `shellcheck-alpine` image was changed to behave more like the `alpine` image in commit dc1e7c1bd4f.

**Comment by BeyondEvil** [comment]
Thanks for the explanation @koalaman ! 🙏
