### ISSUE TITLE
Issue with echo statements and multiline

### ISSUE THREAD

**Issue by cbitterfield** [koalaman/shellcheck#1762]
#### For bugs
- Rule Id (if any, e.g. SC1000): 
- My shellcheck version (`shellcheck --version` or "online"): 
- [ ] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [ ] I tried on shellcheck.net and verified that this is still a problem on the latest commit

#### For new checks and feature suggestions

$ shellcheck myscript
 
Line 55:
echo -e $"$USER_PASSWORD\n$USER_PASSWORD\n" | passwd dev_site
                                          ^-- SC1078: Did you forget to close this double quoted string?
 
You need a better example of how to fix this. This is a common need. When you test this one line in another window, there is not an issue
![Screen Shot 2019-11-27 at 10 35 55 AM](https://user-images.githubusercontent.com/11802951/69750579-eef69b80-1101-11ea-8c3d-2dfd6beb9c63.png)
![Screen Shot 2019-11-27 at 10 35 46 AM](https://user-images.githubusercontent.com/11802951/69750588-f28a2280-1101-11ea-92b8-cf81935c1a9f.png)

related

#### Here's a snippet or screenshot that shows the problem:

```sh

#!/your/interpreter
your script here

```

**Comment by cbitterfield** [comment]
My scripts are available for review on GitHub
github.com:cbitterfield/lemp2.git

There seems to be a difference if checked line by line v the whole file.

**Comment by gromgit** [comment]
First, please don't use screenshots as examples. Post the actual offending code as text, either inline or in a gist. That way, others can copy/paste and test for themselves, instead of painstakingly (mis)transcribing from an image.

Second, please don't rely on live repos when posting issues, as others would then have to dig through your commit history to find the original code. I took the trouble to find [the original file+commit](https://github.com/cbitterfield/lemp/blob/590baab0808456ff3f584c4322bb1808cb267c2f/lemp-start) that looks like your screenshot, but I can no longer replicate this issue.

If you think it's still a "live" issue, please post a proper code snippet that anyone can copy, paste, and test for themselves. Otherwise, please consider closing this issue.

**Comment by cbitterfield** [comment]
Good Points. I checked the script from using echo to using printf. So the issue when away. I tested with the lastest version and I can't replicate the issue.
