### ISSUE TITLE
Setup.hs is broken with Cabal 3.x

### ISSUE THREAD

**Issue by peti** [koalaman/shellcheck#1778]
When trying to build `ShellCheck-0.7.0` with `ghc-8.8.1`, the build fails during the configure stage:

~~~
Setup.hs:6:3: error:
    Module ‘Distribution.Simple’ does not export ‘UserHooks(preSDist)’
  |
6 |   UserHooks ( preSDist ),
  |   ^^^^^^^^^^^^^^^^^^^^^^
~~~~

Apparently, `Setup.hs` needs an overhaul for Cabal 3.x compatibility.

**Comment by koalaman** [comment]
Indeed it is. It should be fixed in the latest git version though. Can you give it a try?

**Comment by athas** [comment]
I can confirm that that git HEAD works with Cabal 3.x.

**Comment by cole-h** [comment]
I know this is in bad form, and I really do hate to do this, but is there any chance of a new release in order to close this issue in the near future?

ShellCheck has been marked as broken on NixOS and is causing evaluations to fail (see: https://github.com/NixOS/nixpkgs/commit/7ecd6958b996f2f4bc1e893285cec4ced3f3301c#comments) as a result of 0.7.0 being incompatible.

Sorry for being That Guy™.

**Comment by jonringer** [comment]
I created PR which will remedy this until the next release

**Comment by peti** [comment]
Thank you very much for the fix!
