### ISSUE TITLE
Allow shellcheck ignore to ignore a block of code

### ISSUE THREAD

**Issue by XaaT** [koalaman/shellcheck#1965]
# Feature suggestion

Allow shecllcheck to ignore a whole block of code
Eg. when using "cat <<EOF something EOF"

## Here's what shellcheck currently says:
```
Line 165:
if [ "$grub_platform" = "efi" ]; then
      ^-- SC2154: grub_platform is referenced but not assigned.
```

## Here's what I wanted or expected to see:
Nothing

**Comment by rockandska** [comment]
Allowing "disable" on a whole block will be also useful for this kind of cases where local variables are shared between internal functions

```
test() {
  local a
  local b
  local c
}

a() {
  echo $a
}
```

Right now, could be rewritten as below but prefer the version with local on independent lines
```
test() {
  local a b c
}
```

**Comment by koalaman** [comment]
Since directives are scoped to commands and not to lines, you can use them before functions to apply them only to that entire function. You can also make creative use of brace groups to define an arbitrary block to ignore in:

```
#!/bin/bash
: # this is a dummy command so that the directive isn't the first thing in the file and therefore filewide

# This directive only applies to the `test` function (all of it)
# shellcheck disable=SC2034
test() {
  local a
  local b
  local c
}

test2() {
  # Still triggers
  local d 
  # This directive only applies to `e` and `f`
  # shellcheck disable=SC2034
  {
    local e
    local f
  }
}

test3() {
  # Still triggers
  local g
}
```

It's not entirely the same thing, but generally close enough.

@XaaT Note that ShellCheck is right in this case: the here doc delimiter is not quoted so variables in the contents will be expanded by the current shell and result in an output of `if [ "" = "efi" ]`
