### ISSUE TITLE
Add git-describe (with sha1) as version text to Shellcheck

### ISSUE THREAD

**Issue by stdedos** [koalaman/shellcheck#2330]
Especially with the https://github.com/koalaman/shellcheck/releases/tag/latest build, `shellcheck --version` returning a version string in the format

> v0.7.2-56-g4e703e5

would make it much easier to identify from where is the latest release built out of.

If, for some reason, you prefer the `Version: xxx` field to have the specific parsing (backwards compatible), add an extra line with that information.

**Comment by koalaman** [comment]
I've wanted this for a while, but didn't know how to make it happen since the version number is fetched via Cabal to avoid going out of sync. I worked around it by adding a CI kludge that swaps out the source code. `docker run -t koalaman/shellcheck:latest --version` now shows `v0.7.2-64-gdb4701d`. Thanks!
