### ISSUE TITLE
Mirror ShellCheck wiki somewhere search engines can index

### ISSUE THREAD

**Issue by dimo414** [koalaman/shellcheck#2487]
*I'm sure this is a known issue, but I searched and didn't see anything relevant in the ShellCheck repo; sorry if this is noisy*

Unfortunately, due to https://github.com/github/feedback/discussions/4992 the ShellCheck wiki doesn't show up in Google for searches like \[[SC2086](https://google.com/search?q=SC2086)\]; https://github-wiki-see.page/ sometimes shows up in its place, but it's a poor substitute (for the longest time I thought it was a spam mirror like you see for StackOverflow questions and intentionally avoided clicking on it).

It's possible GitHub will eventually lift this restriction or change the requirements to allow the ShellCheck wiki to be indexable once more, but I'd argue it'd still be better to host this important documentation elsewhere (e.g. on ShellCheck.net) even if GitHub's policy changes.

**Comment by nelsonjchen** [comment]
I run https://github-wiki-see.page/ so I'm very aware of the current situation. 

Here's another option as well. I'm just presenting it but I don't have a preference for it or any other solution. 

Since this repository has so many stars (more than 1000+, by a lot!), an approach like what the VSCode for Go extension people did is possible as well if one wants to "preserve" the GitHub Wiki UI/URLs:

https://github.com/golang/vscode-go/issues/2094

Wikis on 1000 star+ repositories can be indexed if "Editing Restricted to Repository Collaborators" is turned on. What the VSCode for Go people did was take advantage of that to deploy to the Wiki from their own GitHub repository. The drawback is that users need to submit pull requests.

**Comment by nelsonjchen** [comment]
A possible way to lessen the hit of locking down the Wiki might be to synthesize Edit on GitHub links into the markdown on the Wiki like [what I've suggested in that issue](https://github.com/golang/vscode-go/issues/2094#issuecomment-1120549623).

**Comment by koalaman** [comment]
ShellCheck already had redirections from e.g. https://www.shellcheck.net/wiki/SC2086 to the GitHub wiki. I've replaced the redirections with statically generated pages. Hopefully the formatting isn't too broken, and they'll be indexed by search engines soon.

**Comment by nelsonjchen** [comment]
@koalaman 

Those pages may be a bit invisible to search engines at the moment as they aren't linked anywhere, accessible some sort of index page of some sort, or visible through a sitemap. Users may be visiting them through browsers after copy/clicking them from the terminal but otherwise they aren't very "visible".

Adding a sitemap would probably be the quickest way to get them into the indexes of many search engines. Being able to get to them from the front page by clicking through web pages would also probably help their ranking a lot as well.

You can measure how indexed those new static pages are at least on Google by looking at the https://search.google.com/search-console and adding a sitemap. 

Here's a glimpse into GHWSEE's debug view of its effectiveness on shellcheck's GitHub Wiki stuff as seen through Google's Search Console:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/5363/167777930-7ba0a204-a217-4c41-9175-06aa0ac6043e.png">

Equivalent systems exist for Bing (which also provide much of their index to DuckDuckGo).

---

By the way, I cannot figure out a way to automatically disable GHWSEE with this kind of arrangement as there's no way to detect that a project has decided to mirror their Wiki onto an indexable site non-expensively. Any way that looks more official and kicks the service I built's ranking down will work for shellcheck's needs while I don't have this manually added to GHWSEE. 

I have an existing manual blacklist system of which I'm looking forward to adding shellcheck to soon. I want to wait until you have that indexing issue solved and monitored though.

**Comment by koalaman** [comment]
Don't worry, there's a complete index on https://www.shellcheck.net/wiki/ plus https://www.shellcheck.net/wiki/sitemap.txt which I already submitted to Google

**Comment by nelsonjchen** [comment]
Solved and monitored! Cool! I'll blacklist when I am able to then. 👍
