### ISSUE TITLE
separate tests from src modules

### ISSUE THREAD

**Issue by juhp** [koalaman/shellcheck#254]
ShellCheck.Simple, ShellCheck.Analytics, and ShellCheck.Parser currently export QuickCheck tests and so require functioning TemplateHaskell to build.

But ghc only really support TemplateHaskell well on x86\* archs,
so currently it is difficult to build ShellCheck on other archs like arm and ppc.

Could you please separate out the QuickCheck tests from ShellCheck/ into test/
so that it is possible to build ShellCheck itself (without the tests) on architectures
without TemplateHaskell?

**Comment by koalaman** [comment]
This has come up before, but separating them out would be pretty annoying during development.

What if there was an official script or other trivial way to strip TemplateHaskell from the source files?

**Comment by juhp** [comment]
Well the aforementioned TemplateHaskell restriction no longer holds for ghc-7.10+.
Nevertheless the architecture seems a bit unusual...
why is it hard for ShellCheck to do it separately - do you need some internal module to do it?

Anyway QuickCheck is a bit of a heavy dependency so I still suggest it is better to separate out test code.

**Comment by koalaman** [comment]
I'm definitely willing to be convinced, but it currently seems like a pain due to the lack of tooling.

Currently, adding a test is a single line of code next to the test.

With a separate file, it seems like you would have to 1.  export the function being tested in the module, 2. open a different file, 3. search for the appropriate place, and 4. add the test. Given that a typical test is something like `verify someFunction "foo --bar=baz"`, that's a fairly large overhead.

Any input on how to improve on this is appreciated.

**Comment by koalaman** [comment]
With 32af2783 you can strip out the unit tests to remove both the QuickCheck and TemplateHaskell dependencies

**Comment by juhp** [comment]
Thanks, this looks good to me :+1: :-)
