### ISSUE TITLE
Silencing specific lines with `# noqa` or smth similar

### ISSUE THREAD

**Issue by teferi** [koalaman/shellcheck#275]
Some errors state that I can verify the line (or at least that's what I imagine that message means) but I couldn't find anything like that in the docs. 

Pep8/pyflakes has a very nice feature, that if you leave a comment `# noqa` or `# NOQA` after problematic line — pep8 would ignore the line completely. This might be usefull, if you do not want to ignore the issue completely (with --exlude option) and know exactly what you're doing in this specific line and want to suppress the error.

It would be nice if you could implement smth similar.

**Comment by ormaaj** [comment]
My favorite implementation is clang's [#pragma clang diagnostic push / pop](http://llvm.org/releases/3.4/tools/clang/docs/UsersManual.html#controlling-diagnostics-via-pragmas) because you just define a block region wherein warnings are modified from the surrounding state.

Definitely a nice feature. It makes it explicit in the code that a particular warning is expected.

**Comment by koalaman** [comment]
Use a shellcheck directive: https://github.com/koalaman/shellcheck/wiki/Directive

**Comment by ormaaj** [comment]
Oh,  it exists. Awesome!
