### ISSUE TITLE
Single-iteration loops ("once" blocks) shouldn't be forbidden ?

### ISSUE THREAD

**Issue by strk** [koalaman/shellcheck#2839]
Or why should them ? Do you recommend an alternative ?
There is no alternative written in https://www.shellcheck.net/wiki/SC2043 but I think it's pretty common to use run-once loops to help readability.

See https://github.com/qgis/QGIS/pull/54847#issuecomment-1748630050

**Comment by brother** [comment]
If you want to keep the loop just ignore SC2043 for that line.

**Comment by koalaman** [comment]
I had an empirical look on a larger corpus, and it seems to be about 50-50 whether these are intentional or something like `for i in {1}`, `for i in 0..3`, `for value in array`, `for file in variablewithglobs`, `for line in file`, `for file in /my/dir`. I edited the wiki to suggest ignoring if this is a stylistic choice. Thanks!
