### ISSUE TITLE
SC2006 incorrectly reports that the use of backquotes for command substitution is deprecated

### ISSUE THREAD

**Issue by dderby** [koalaman/shellcheck#290]
I don't know about other shells but the use of backquotes for command substitution is not deprecated in the POSIX shell.

Here is a link to the relevant part of the POSIX.1-2008 specification.  You will see that it does not say anywhere that it is deprecated:

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_03

It even states that it's perfectly acceptable to nest them by preceding inner backquotes with backslash characters, however I personally would always use the $(command) syntax when nesting.

**Comment by dderby** [comment]
I've just spotted the related wiki page (https://github.com/koalaman/shellcheck/wiki/SC2006).

Could you please elaborate on points 1 and 2 of the Rationale?

**Comment by koalaman** [comment]
They're both described in the link you post:

>if a non-escaped backquote is encountered within a shell comment, a here-document, an embedded command substitution of the $(command) form, or a quoted string, undefined results occur

and

>Within the backquoted style of command substitution, <backslash> shall retain its literal meaning, except when followed by: '$', '`', or <backslash>.

The latter is surprising because you can take a command like `echo -e "foo\nbar"` and put it in backticks, but not a command like `echo -e "foo\$bar"`. 

You're right though, "deprecated" is more wishful thinking than technical fact. I changed it to "legacy" in 895d83a.
