### ISSUE TITLE
SC2012: `find` is not an adequate replacement for `ls -ld` piped to `cut`

### ISSUE THREAD

**Issue by stuartpb** [koalaman/shellcheck#302]
See https://github.com/plushu/plushu/blob/master/bin/plushu#L20:

```bash
    PLUSHU_USER=`ls -ld "$PLUSHU_ROOT" | cut -d' ' -f3`
```

This is to determine the owner of a directory - it cannot be determined using `find`, and will have no problem with paths with filenames.

**Comment by dualbus** [comment]
On Thu, Feb 05, 2015 at 06:12:46PM -0800, Stuart P. Bentley wrote:
> See https://github.com/plushu/plushu/blob/master/bin/plushu#L20:
> 
> ```bash
>     PLUSHU_USER=`ls -ld "$PLUSHU_ROOT" | cut -d' ' -f3`
> ```
> 
> This is to determine the owner of a directory - it cannot be determined using `find`, and will have no problem with paths with filenames.
'ls' use is to be avoided, in this case not because of the file name, but
because its output isn't stable across multiple UNIX variants:

openbsd
 $ ls -ld
 drwxr-xr-x  3 dualbus  dualbus  512 Jan 24 14:35 .
 $ ls -ld|cut -d' ' -f3
 3

netbsd
 $ ls -ld
 drwx------  9 dualbus  arpa  512 Feb  6 06:36 .
 $ ls -ld|cut -d' ' -f3
 9

linux:
 dualbus@hp ~ % ls -ld
 drwxr-xr-x 57 dualbus dualbus 20480 Feb  6 00:37 .
 dualbus@hp ~ % ls -ld|cut -d' ' -f3
 dualbus

In this case it'd seem that you can get away with it if you change cut with
awk '{print $3}'

But in general, ls output is to be used interactively only. It's not stable
enough for use in scripts, and it's better if shellcheck keeps recommending
that.

**Comment by acatton** [comment]
Yes but `stat --format="%U" "$PLUSHU_ROOT"` is.

**Comment by qzerolee** [comment]
As @dualbus says "ls output is to be used interactively only", you can use "stat" instead, which is part of GNU coreutils (https://www.gnu.org/software/coreutils/).

**Comment by dualbus** [comment]
On Fri, Feb 06, 2015 at 02:40:41AM -0800, Q. Zero Lee wrote:
> As @dualbus says "ls output is to be used interactively only", you can use "stat" instead, which is part of GNU coreutils (https://www.gnu.org/software/coreutils/).
Just a small nitpick: If you're already depending on having stat (GNU
coreutils), you might as well assume that you have GNU ls, since it's part of
coreutils also.

dualbus@hp ~ % dpkg -S /bin/ls
coreutils: /bin/ls

In this case there seems to be no viable standard way of doing it, so :-) yeah

**Comment by koalaman** [comment]
GNU `find . -printf "%u\n"`, but yes, it's a good point. I've updated the wiki to suggest using `stat` on supported platforms for when it's not the filename you're interested in.

The error message is still misleading in this case, but I'll leave it the details to the wiki for now.

**Comment by stuartpb** [comment]
Of course, the trouble is that `stat` has different syntax on BSD than the GNU version.

**Comment by stuartpb** [comment]
I'd say this rule should generally be amended to recommend `ls -l | awk '{print $3}'` or whatever field number over piping to `cut` or using `stat`, since ls output field order is more stable cross-platform than `stat` options.
