### ISSUE TITLE
Shellcheck is excellent. But ran into this.

### ISSUE THREAD

**Issue by gamename** [koalaman/shellcheck#329]
It doesn't seem to understand that $(command) is the same as the old `command`.

So, in the example below, the first message is legit, but the last two are not:

> shellcheck --shell=bash ./build_boxes.sh 

In ./build_boxes.sh line 111:
    new_atlas_version=$(atlas_increment_version ${atlas_version})
                                                ^-- SC2086: Double quote to prevent globbing and word splitting.

In ./build_boxes.sh line 152:
           box_provider="$(basename $(dirname ${line}))"
                                    ^-- SC2046: Quote this to prevent word splitting.
                                              ^-- SC2086: Double quote to prevent globbing and word splitting.

In ./build_boxes.sh line 178:
s=$(/usr/bin/printf -- '+%.s' $(seq 58); echo )
                              ^-- SC2046: Quote this to prevent word splitting.

**Comment by dualbus** [comment]
On Mon, Mar 16, 2015 at 11:48:46AM -0700, Tennis Smith wrote:
> It doesn't seem to understand that $(command) is the same as the old `command`.
Wrong, it does know.

> In ./build_boxes.sh line 152:
>            box_provider="$(basename $(dirname ${line}))"
>                                     ^-- SC2046: Quote this to prevent word splitting.
This message is correct. If $line contains a path, and such path has spaces or
glob characters, that'll result in a mess. See:

    dualbus@hp:~$ line='/path/my-music/my-file.mp3'; box_provider="$(basename
    $(dirname ${line}))"; echo "$box_provider" 
    my-music
    dualbus@hp:~$ line='/path/my music/my file.mp3'; box_provider="$(basename
    $(dirname ${line}))"; echo "$box_provider" 
    basename: extra operand ‘.’
    Try 'basename --help' for more information.
    
    dualbus@hp:~$

> In ./build_boxes.sh line 178:
> s=$(/usr/bin/printf -- '+%.s' $(seq 58); echo )
>                               ^-- SC2046: Quote this to prevent word splitting.
Now, shellcheck doesn't know about seq. Actually, shellcheck doesn't know
about: $(cmd ...) in general. It can't possibly know what the output of an
arbitrary command is, so it just tries to be helpful here. Since you *do* want
the word splitting for seq, you can suppress the message there, or, use brace
expansion:

    s=$(printf '+%.s' {1..58})

(note, that last echo is a no-op, the $(...) expansion trims trailing
newlines).

**Comment by koalaman** [comment]
dualbus is right. The correct quoting in the second case is `box_provider=$(basename "$(dirname "${line}")")`

**Comment by gamename** [comment]
Great! Thank you.
-T
