### ISSUE TITLE
JetBrains Webstorm Integration

### ISSUE THREAD

**Issue by gdbtek** [koalaman/shellcheck#360]
I really do love this tool and I'm wondering if you have a thought to make this tool available as plugin in https://www.jetbrains.com/ IDEs?

Thanks

**Comment by koalaman** [comment]
There's probably already a CheckStyle plugin for these, in which case you can use it with shellcheck's CheckStyle compatible xml output.

**Comment by gdbtek** [comment]
@koalaman , I could not find any plugins for WebStorm that can validate source code as good as shellcheck, not even close. The only plugin available for bash in WebStorm is: http://plugins.jetbrains.com/plugin/?id=4230

**Comment by koalaman** [comment]
I meant that the plugin wouldn't have to support bash at all. You can use a plugin that only supports validating for example C or Java code.

This works because shellcheck can mimic some of the underlying tools these plugins use:

    $ gcc file.c
    file.c:2:3: error: ‘foo’ undeclared (first use in this function)

    $ clang file.c
    file.c:2:3: error: use of undeclared identifier 'foo'; did you mean 'for'?

    $ shellcheck -f gcc file.sh
    file.sh:2:3: error: Double quote array expansions. [SC2068]

Since all these error messages have the same format, any plugin that supports showing errors from `gcc` or `clang` for C code also supports showing errors from ShellCheck, even if they were never intended to support shell scripts.

Similarly, ShellCheck can output CheckStyle XML, which your site lists an IDEA plugin for (but not a WebStorms plugin). 

I don't have access to WebStorms so I can't test or suggest which plugins work well this way. However, it works fine in other editors that nominally only supports `gcc`, like Vim.

**Comment by WindomZ** [comment]
I have a usage in WebStorms.

Go to _File | Settings | Tools | External Tools_ for Windows and Linux, or _WebStorm | Preferences | Tools | External Tools_ for OS X, and click **+** to add a new tool.

- **Name** set `Shellcheck`
- **Program** set `shellcheck`
- **Parameters** set `$FilePathRelativeToProjectRoot$`
- **Working directory** set `$ProjectFileDir$`

![screenshot from 2017-07-02 02-07-26](https://user-images.githubusercontent.com/14875359/27764566-10b0a078-5ecf-11e7-9780-878599964244.png)

If you add hotkey for it.
Go to _File | Settings | Keymap_ for Windows and Linux, _WebStorm | Preferences | Keymap_ for OS X, and type external tool name in search box.

**Comment by light2yellow** [comment]
@WindomZ thanks for this post, I have set up `clang-format` in a similar fashion.

This is a generic way to proceed when there's a binary available, but no inline linter.

**Comment by christopher-hopper** [comment]
You can also use the method above by @WindomZ in conjunction with output filters, so that errors are hyperlinked to the file, line and column.

_Settings | Tools | External Tools_

- Program: `shellcheck`
- Parameters: `-f gcc $FilePath$`
- Working directory: `$ProjectFileDir$`

**Output Filters...**

- Name: `gcc`
- Description: `The gcc output format.`
- Regular expression to match output: `$FILE_PATH$:$LINE$:$COLUMN$`

![screen shot 2017-08-31 at 4 00 51 pm](https://user-images.githubusercontent.com/452515/29908822-6e762d7e-8e66-11e7-9167-7f7026f4fd83.png)

**Comment by hubertgrzeskowiak** [comment]
Hello fellow Googler. Here's what you came for:
# Step 1
Set up external command. Important thing is that the working dir is the root of your system (or your harddrive letter on Windows).
![Step 1](https://user-images.githubusercontent.com/278624/32485437-87863d60-c3f7-11e7-8f5c-5ed5055a158b.png)
# Step 2
Set output filter. It only matches the file name with full path, which is why we run shellcheck in the root dir.
![Step 2](https://user-images.githubusercontent.com/278624/32485457-989bde0c-c3f7-11e7-92ed-6cd00bd9b959.png)
# Step 3
Optionally set up hooks or key bindings.
![Step 3](https://user-images.githubusercontent.com/278624/32485473-a5db96fc-c3f7-11e7-8e77-3814a067d1e5.png)
# Profit
Sample result:
![Profit](https://user-images.githubusercontent.com/278624/32485499-c3274d28-c3f7-11e7-8aa4-b049bb7f5fe7.png)

**Comment by singalen** [comment]
There is a plugin now: https://github.com/pwielgolaski/shellcheck-plugin/

**Comment by koalaman** [comment]
I've linked to this thread from https://github.com/koalaman/shellcheck/wiki/Contrib
