### ISSUE TITLE
SC2006: Use $(..) instead of `` deprecated 

### ISSUE THREAD

**Issue by Maijin** [koalaman/shellcheck#364]
SC2006: Use $(..) instead of deprecated `..`

That's fine but in the wiki, wouldn't be worth to mention that important "Exception"

http://wiki.bash-hackers.org/syntax/expansion/cmdsubst

Catch stdout and preserve trailing newlines:

    var=$(echo -n $'\n'); echo -n "$var"; # $var == ""
    var=$(echo -n $'\n'; echo -n x); var="${var%x}"; echo -n "$var" # $var == "\n"

This adds `x` to the output, which prevents the trailing newlines of the previous commands' output from being deleted by `$(..)`.

By removing this `x` later on, we are left with the previous commands' output with its trailing newlines.

Also:

https://stackoverflow.com/questions/15184358/how-to-avoid-bash-command-substitution-to-remove-the-newline-character?answertab=votes#tab-top

**Comment by radare** [comment]
`` is not deprecated, it just allows to nest two levels if used with $() and its shorter form too. who says that it is deprecated? i know they do different filtering of the output, but its not deprecated iirc

**Comment by Maijin** [comment]
Some others docs related to that topic:

* http://unix.stackexchange.com/a/126928

* http://stackoverflow.com/a/24592916/2170802

**Comment by koalaman** [comment]
@Maijin Both backticks and `$(..)` eat trailing line feeds in exactly the same way, and there are no warnings related to it. I don't really see how this fits into the shellcheck wiki

@radare You're right. This message is from an old version of shellcheck. It's since been changed to "legacy". Backticks are discouraged because they have undefined behavior, surprising escaping issues and are hard to nest.

**Comment by Maijin** [comment]
@koalaman Yes I've noticed that afterwards :full_moon_with_face:

**Comment by koalaman** [comment]
Ok, I'll close this one
