### ISSUE TITLE
Can't update cabal-install

### ISSUE THREAD

**Issue by lanzonij** [koalaman/shellcheck#372]
I am trying to install shellint on my Linux version 2.6.32-358.el6.x86_64 (Red Hat 4.4.7-3). I need to install cabal first. As suggested at https://github.com/koalaman/shellcheck, I run

yum install cabal-install

and I get cabal-install version 0.10.2 using version 1.10.2.0 of the Cabal library. Then

cabal update
cabal install cabal-install

But I get the following output

Resolving dependencies...
cabal: cannot configure Cabal-1.22.3.0. It requires base >=4.4 && <5
For the dependency on base >=4.4 && <5 there are these packages: base-4.4.0.0,
base-4.4.1.0, base-4.5.0.0, base-4.5.1.0, base-4.6.0.0, base-4.6.0.1,
base-4.7.0.0, base-4.7.0.1, base-4.7.0.2 and base-4.8.0.0. However none of
them are available.
base-4.4.0.0 was excluded because base-4.3.1.0 was selected instead
base-4.4.0.0 was excluded because of the top level dependency base -any
base-4.4.1.0 was excluded because base-4.3.1.0 was selected instead
base-4.4.1.0 was excluded because of the top level dependency base -any
base-4.5.0.0 was excluded because base-4.3.1.0 was selected instead
base-4.5.0.0 was excluded because of the top level dependency base -any
base-4.5.1.0 was excluded because base-4.3.1.0 was selected instead
base-4.5.1.0 was excluded because of the top level dependency base -any
base-4.6.0.0 was excluded because base-4.3.1.0 was selected instead
base-4.6.0.0 was excluded because of the top level dependency base -any
base-4.6.0.1 was excluded because base-4.3.1.0 was selected instead
base-4.6.0.1 was excluded because of the top level dependency base -any
base-4.7.0.0 was excluded because base-4.3.1.0 was selected instead
base-4.7.0.0 was excluded because of the top level dependency base -any
base-4.7.0.1 was excluded because base-4.3.1.0 was selected instead
base-4.7.0.1 was excluded because of the top level dependency base -any
base-4.7.0.2 was excluded because base-4.3.1.0 was selected instead
base-4.7.0.2 was excluded because of the top level dependency base -any
base-4.8.0.0 was excluded because base-4.3.1.0 was selected instead
base-4.8.0.0 was excluded because of the top level dependency base -any

Something has gone wrong, because if I cd into the /shellcheck directory and run

cabal install

what I get is again

Resolving dependencies...
cabal: cannot configure directory-1.2.2.1. It requires base >=4.5 && <4.9
For the dependency on base >=4.5 && <4.9 there are these packages:
base-4.5.0.0, base-4.5.1.0, base-4.6.0.0, base-4.6.0.1, base-4.7.0.0,
base-4.7.0.1, base-4.7.0.2 and base-4.8.0.0. However none of them are
available.
base-4.5.0.0 was excluded because base-4.3.1.0 was selected instead
base-4.5.0.0 was excluded because of the top level dependency base -any
base-4.5.1.0 was excluded because base-4.3.1.0 was selected instead
base-4.5.1.0 was excluded because of the top level dependency base -any
base-4.6.0.0 was excluded because base-4.3.1.0 was selected instead
base-4.6.0.0 was excluded because of the top level dependency base -any
base-4.6.0.1 was excluded because base-4.3.1.0 was selected instead
base-4.6.0.1 was excluded because of the top level dependency base -any
base-4.7.0.0 was excluded because base-4.3.1.0 was selected instead
base-4.7.0.0 was excluded because of the top level dependency base -any
base-4.7.0.1 was excluded because base-4.3.1.0 was selected instead
base-4.7.0.1 was excluded because of the top level dependency base -any
base-4.7.0.2 was excluded because base-4.3.1.0 was selected instead
base-4.7.0.2 was excluded because of the top level dependency base -any
base-4.8.0.0 was excluded because base-4.3.1.0 was selected instead
base-4.8.0.0 was excluded because of the top level dependency base -any

Any help

**Comment by georgeryoung** [comment]
I have a very similar problem:
cabal install --upgrade-dependencies --verbose=3 shellcheck 
searching for ghc in path.
found ghc at /usr/bin/ghc
("/usr/bin/ghc",["--numeric-version"])
/usr/bin/ghc is version 7.0.4
looking for tool "ghc-pkg" near compiler in /usr/bin
found ghc-pkg in /usr/bin/ghc-pkg
("/usr/bin/ghc-pkg",["--version"])
/usr/bin/ghc-pkg is version 7.0.4
("/usr/bin/ghc",["--supported-languages"])
("/usr/bin/ghc",["--info"])
Reading installed packages...
("/usr/bin/ghc-pkg",["dump","--global","-v2"])
("/usr/bin/ghc-pkg",["dump","--user","-v2"])
("/usr/bin/ghc",["--print-libdir"])
Reading available packages...
Resolving dependencies...
selecting ShellCheck-0.3.7 (hackage) and discarding QuickCheck-1.0, 1.1.0.0,
1.2.0.0, 1.2.0.1, 2.1, 2.1.0.1, 2.1.0.2, 2.1.0.3, 2.1.1, 2.1.1.1, 2.1.2, 2.2,
2.3, 2.3.0.1, 2.3.0.2, 2.4, 2.4.0.1, 2.4.1, 2.4.1.1, 2.4.2, 2.5, 2.5.1,
2.5.1.1, 2.6, 2.7, 2.7.1, 2.7.2, 2.7.3, ShellCheck-0.3.0, 0.3.1, 0.3.2, 0.3.3,
0.3.4, 0.3.5 and 0.3.6
selecting base-4.3.1.0 (installed) and discarding integer-gmp-0.5.1.0 and
1.0.0.0
selecting ghc-prim-0.2.0.0 (installed)
selecting integer-gmp-0.2.0.3 (installed)
selecting rts-1.0 (installed)
selecting regex-tdfa-1.2.0 (hackage) and discarding array-0.1.0.0, 0.2.0.0,
0.3.0.0, 0.3.0.1, 0.3.0.2, 0.3.0.3, regex-base-0.71, 0.72.0.1, 0.72.0.2, 0.83,
0.90, 0.91, 0.92, 0.93, regex-tdfa-0.92, 0.94, 0.95.1, 0.95.2, 0.97.1, 0.97.3,
0.97.4, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.6, 1.1.7 and 1.1.8
selecting json-0.9.1 (hackage) and discarding json-0.3.3, 0.3.6, 0.4.1, 0.4.2,
0.4.3, 0.4.4, 0.5, 0.6, 0.7, 0.8, 0.9, syb-0.1.0.0, 0.1.0.1, 0.1.0.2, 0.1.0.3,
0.2, 0.2.1, 0.2.2, 0.3, 0.3.1 and 0.3.2
selecting parsec-3.1.9 (hackage) and discarding parsec-2.0, 2.1.0.0, 2.1.0.1,
3.0.0, 3.0.1, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8
and text-0.1
selecting syb-0.5.1 (hackage) and discarding syb-0.3.3, 0.3.4, 0.3.5, 0.3.6,
0.3.6.1, 0.3.6.2, 0.3.7, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4 and 0.5
selecting containers-0.5.6.3 (hackage) and discarding containers-0.1.0.0,
0.1.0.1, 0.2.0.0, 0.2.0.1, 0.3.0.0, 0.4.0.0, 0.4.1.0, 0.4.2.0, 0.4.2.1,
0.5.0.0, 0.5.1.0, 0.5.2.0, 0.5.2.1, 0.5.3.0, 0.5.3.1, 0.5.4.0, 0.5.5.0,
0.5.5.1, 0.5.6.0, 0.5.6.1, 0.5.6.2, deepseq-1.0.0.0, 1.1.0.0, 1.1.0.1 and
1.1.0.2
selecting deepseq-1.4.1.1 (hackage) and discarding deepseq-1.2.0.0, 1.2.0.1,
1.3.0.0, 1.3.0.1, 1.3.0.2, 1.4.0.0 and 1.4.1.0
selecting text-1.2.1.1 (hackage) and discarding text-0.2, 0.3, 0.4, 0.5, 0.6,
0.7, 0.7.0.1, 0.7.1.0, 0.7.2.1, 0.8.0.0, 0.8.1.0, 0.9.0.0, 0.9.0.1, 0.9.1.0,
0.10.0.0, 0.10.0.1, 0.10.0.2, 0.11.0.0, 0.11.0.1, 0.11.0.2, 0.11.0.3,
0.11.0.4, 0.11.0.5, 0.11.0.6, 0.11.0.7, 0.11.0.8, 0.11.1.0, 0.11.1.1,
0.11.1.2, 0.11.1.3, 0.11.1.5, 0.11.1.6, 0.11.1.7, 0.11.1.8, 0.11.1.9,
0.11.1.10, 0.11.1.11, 0.11.1.12, 0.11.1.13, 0.11.2.0, 0.11.2.1, 0.11.2.2,
0.11.2.3, 0.11.3.0, 0.11.3.1, 1.0.0.0, 1.0.0.1, 1.1.0.0, 1.1.0.1, 1.1.1.0,
1.1.1.1, 1.1.1.2, 1.1.1.3, 1.1.1.4, 1.2.0.0, 1.2.0.2, 1.2.0.3, 1.2.0.4,
1.2.0.5, 1.2.0.6 and 1.2.1.0
selecting binary-0.7.5.0 (hackage) and discarding binary-0.2, 0.3, 0.4, 0.4.1,
0.4.2, 0.4.3, 0.4.3.1, 0.4.4, 0.4.5, 0.5, 0.5.0.1, 0.5.0.2, 0.5.1.0, 0.5.1.1,
0.6.0.0, 0.6.1.0, 0.6.2.0, 0.6.3.0, 0.6.4.0, 0.7.0.0, 0.7.0.1, 0.7.1.0,
0.7.2.0, 0.7.2.1, 0.7.2.2, 0.7.2.3, 0.7.3.0 and 0.7.4.0
selecting regex-base-0.93.2 (hackage) and discarding regex-base-0.93.1
selecting bytestring-0.10.6.0 (hackage) and discarding bytestring-0.9,
0.9.0.1, 0.9.0.2, 0.9.0.3, 0.9.0.4, 0.9.1.0, 0.9.1.1, 0.9.1.2, 0.9.1.3,
0.9.1.4, 0.9.1.5, 0.9.1.6, 0.9.1.7, 0.9.1.8, 0.9.1.9, 0.9.1.10, 0.9.2.0,
0.9.2.1, 0.10.0.0, 0.10.0.1, 0.10.0.2, 0.10.2.0, 0.10.4.0 and 0.10.4.1
selecting
cabal: cannot configure directory-1.2.2.1. It requires base >=4.5 && <4.9
For the dependency on base >=4.5 && <4.9 there are these packages:
base-4.5.0.0, base-4.5.1.0, base-4.6.0.0, base-4.6.0.1, base-4.7.0.0,
base-4.7.0.1, base-4.7.0.2 and base-4.8.0.0. However none of them are
available.
base-4.5.0.0 was excluded because base-4.3.1.0 was selected instead
base-4.5.0.0 was excluded because of the top level dependency base -any
base-4.5.1.0 was excluded because base-4.3.1.0 was selected instead
base-4.5.1.0 was excluded because of the top level dependency base -any
base-4.6.0.0 was excluded because base-4.3.1.0 was selected instead
base-4.6.0.0 was excluded because of the top level dependency base -any
base-4.6.0.1 was excluded because base-4.3.1.0 was selected instead
base-4.6.0.1 was excluded because of the top level dependency base -any
base-4.7.0.0 was excluded because base-4.3.1.0 was selected instead
base-4.7.0.0 was excluded because of the top level dependency base -any
base-4.7.0.1 was excluded because base-4.3.1.0 was selected instead
base-4.7.0.1 was excluded because of the top level dependency base -any
base-4.7.0.2 was excluded because base-4.3.1.0 was selected instead
base-4.7.0.2 was excluded because of the top level dependency base -any
base-4.8.0.0 was excluded because base-4.3.1.0 was selected instead
base-4.8.0.0 was excluded because of the top level dependency base -any
[14:27:47][release@qco55srv01:~ 1]$  

Does anyone have a workaround suggestion?

**Comment by koalaman** [comment]
It appears that the GHC version you have installed, 7.0.4, is four years out of date. For comparison, Debian Stable is on 7.4.1, from two years ago. 

Can you install a more recent version?

**Comment by lanzonij** [comment]
Thanks koalaman, this has solved my issue.
