### ISSUE TITLE
Japanese char issue on Windows(2)

### ISSUE THREAD

**Issue by Xanardi** [koalaman/shellcheck#394]
Is a problem that occurred in the Windows version only .
When the Japanese string is mixed in shell script, it becomes an error .
# Console log

> C:\Temp>shellcheck.exe test.sh
> shellcheck.exe: test.sh: hGetContents: invalid argument (invalid byte sequence)
# Script sample

> # !/bin/bash
> 
> a=20
> # あいうえお

**Comment by koalaman** [comment]
The terminal must use UTF-8.

In cmd.exe: `chcp 65001`. It works, but badly:

![image](https://cloud.githubusercontent.com/assets/2818758/8273065/199863b6-1812-11e5-83ba-8115cc8292ef.png)

It is better in Powershell ISE, `chcp 65001`  and `[Console]::OutputEncoding = [System.Text.Encoding]::UTF8`:

![image](https://cloud.githubusercontent.com/assets/2818758/8273141/a5a49da0-1814-11e5-85ca-cfb5c2913666.png)

It works on Linux because UTF-8 is the default. Without UTF-8, it is the same problem as on Windows:

![image](https://cloud.githubusercontent.com/assets/2818758/8273118/fce29348-1813-11e5-9622-2a80babfc94e.png)

**Comment by Xanardi** [comment]
The cause started from the console went well .
I want to call from the front-end (SublimeLinter-shellcheck) without a cmd.exe.
What will you do?

**Comment by koalaman** [comment]
This should now work: ShellCheck 0.4.6 always decodes as UTF-8, regardless of the current system settings.
