### ISSUE TITLE
SC2059 does not seem to protect against multiple variables

### ISSUE THREAD

**Issue by travi** [koalaman/shellcheck#397]
If a `printf` statement references multiple variables, replacing one of them with `%s` and passing the variable as a second argument to `printf` satisfies this check. Instead, it should check that all variables are replaced with `%s` and passed as additional arguments to `printf`

**Comment by koalaman** [comment]
You're right, shellcheck doesn't warn about variables in the format string if the format string already contains format specifiers. 

This is intentional: if you use format specifiers you probably know how printf works, and any decision to mix formatters with variables is well informed. In practice most of these cases are legitimate, using the variables for ansi escapes or variable width formatting. 

ShellCheck's tradeoff was therefore to have a few false negatives over a lot of false positives.

**Comment by travi** [comment]
makes sense. while i understand printf's format, its not natural for me. i was hoping to let shellcheck catch my oversights, but i can understand the tradeoff

**Comment by deryni** [comment]
Candidate for the paranoid mode that's been discussed before?
