### ISSUE TITLE
Erroneous SC2140 when using alias + quotes

### ISSUE THREAD

**Issue by cdown** [koalaman/shellcheck#418]
Unless I'm misunderstanding, I think this instance of SC2140 is mistaken:

    alias "$cmd"="$cmd -s"
                ^-- SC2140: The double quotes around this do nothing. Remove or escape them.

In both of the double quoted sections, not quoting affects word splitting.

This is with ShellCheck-0.3.8.

**Comment by koalaman** [comment]
It's pointing to the `=` sign and wondering why you decided to add no-op quotes instead of doing 

    alias "$cmd=$cmd -s"

In your case they're just superfluous, but in cases like `echo "<img src="foo.png" />" > file.html` this indicates a problem. 

This message needs a rephrasing and should probably be suppressed when the quoted part is `=` or maybe even non-alphabetical

**Comment by cdown** [comment]
Ah, I see now; thanks for the explanation. Yeah, this message is unclear to me, not quite sure how to phrase it though.

**Comment by koalaman** [comment]
In 6d9e847 it will instead say

    Word is on the form "A"B"C" (B indicated). Did you mean "ABC" or "A\"B\"C"?

Hopefully that's less confusing.

**Comment by cdown** [comment]
Great, thanks!
