### ISSUE TITLE
Some rule violations (SC2103, SC2164) found by the online analyzer but not by a local installation

### ISSUE THREAD

**Issue by jonathantaglione** [koalaman/shellcheck#434]
Hello, I have the following script:

    #!/bin/sh
    tar -xvjf ghc-7.8.3-i386-unknown-linux-centos65.tar.bz2
    cd ghc-7.8.3
    ./configure
    make install
    cd ..

With the online analyzer at www.shellcheck.net, I have the following warnings:

   1  #!/bin/sh
   2  #(as root in root's $HOME with all required archives in root's $HOME)
   3  tar -xvjf ghc-7.8.3-i386-unknown-linux-centos65.tar.bz2
   4  cd ghc-7.8.3
      ^––SC2103 Consider using ( subshell ) or 'cd foo||exit' instead.
      ^––SC2164 Use cd ... || exit in case cd fails.
   5  ./configure
   6  make install
   7  cd ..
      ^––SC2164 Use cd ... || exit in case cd fails.

But with a shellcheck-0.3.8 executable I have no warning or error (tested both on CentOS and Windows, and I ran the tests "cabal test" for the unit tests, without problems.)

Other errors/warnings/style... are found correctly by the local installations, I do not have the exact list of what works/what doesn't.

Did I miss something? Is this expected behaviour?
BTW thank yoy so much for this tool!
Jonathan

**Comment by koalaman** [comment]
The online version is always synced against the latest git commit, so it includes all the features that were added in the month and a half since 0.3.8 was released. These are some of them. 

If you want to live on the edge -- possibly with some rough edges, like #435 I just filed for SC2103 and SC2164 overlapping in your example -- you can sync and compile directly from the git repository. Alternatively, you can just sit tight and wait for the next release.
