### ISSUE TITLE
grep with '<'

### ISSUE THREAD

**Issue by ctesniere** [koalaman/shellcheck#448]
Hi,

If it is written : `grep 'word' < filename`
It is preferred that ShellCheck my suggest `grep 'word' filename` ?

**Comment by kurahaupo** [comment]
Sorry, is that an assertion, a question, or a request?

**Comment by ctesniere** [comment]
sorry for my english, this issue is a question :)

**Comment by koalaman** [comment]
I see what you mean, it does look cleaner and I would prefer without `<`. There is no benefit in terms of efficiency or correctness though, so there's little point in trying to get people to change it.

With something like `cat .. | grep`, unnecessary processes are started, so there it matters more and that's why there's a message for it.

**Comment by deryni** [comment]
The only potentially meaningful difference between the two, that I can think of, is the difference in timing of when the file is opened (and how that might change race conditions). There may also be differences in how grep can operate on the input when it comes from standard input versus when it comes from an opened file (though grep might be smart enough to figure that out and work around it). I don't think either of those is material enough to warrant a warning/comment/etc. in either direction though.
