### ISSUE TITLE
Useless cat when piping through several commands?

### ISSUE THREAD

**Issue by mosbth** [koalaman/shellcheck#453]
```
cat ircLog.txt | grep "pansar" | grep "notepad" > b.txt
    ^-- SC2002: Useless cat. Consider 'cmd < file | ..' or 'cmd file | ..' instead.
```

or

```
cat ircLog.txt | grep '<@wasa>' | head -3 | tail -1 > e.txt
    ^-- SC2002: Useless cat. Consider 'cmd < file | ..' or 'cmd file | ..' instead.
```

The examples might look a bit odd, but its exercises in a course to learn the basics of how to combine unix commands with piping, input and output.

If this is useless cat, how should it be done, or perhaps should I just exclude that rule? Whats your advice?

**Comment by lucy** [comment]
`grep "pansar" ircLog.txt | grep "notepad" > b.txt` or
`grep "pansar" < ircLog.txt | grep "notepad" > b.txt`

**Comment by deryni** [comment]
Or `awk '/pansar/ && /notepad/' ircLog.txt > b.txt` but that avoids the pipeline entirely so that's not necessarily exactly relevant. =)

**Comment by koalaman** [comment]
These are indeed [Useless Uses Of Cat](https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat) as lucy demonstrates. It doesn't matter if it's single or multiple commands, it's all just piping:

    grep '<@wasa>' ircLog.txt | head -3 | tail -1 > f.txt

It's not necessarily unreasonable to ignore, but if you choose to do so it should be because you're equally comfortable writing it both ways and you're aware of the effect this will have on efficiency and correctness in each particular case.

**Comment by aw-altiscale** [comment]
What's fun is that:

```bash
grep '<@wasa>' ircLog.txt | head -3 | tail -1 > f.txt
```

may suffer from the #429 issue if that grep generates a lot of output.... ;)

**Comment by deryni** [comment]
Assuming `grep` isn't set up to ignore SIGPIPE (which it probably is/should be) at least.
