### ISSUE TITLE
SC numbers: should SC21{58..61} be (partially) merged?

### ISSUE THREAD

**Issue by Arthur2e5** [koalaman/shellcheck#490]
It seems that SC2158-2161 are basically the same thing. Since GitHub Wiki doesn't have redirection (oh, maybe we can try symlinks?), it sounds better to put them together.

**Comment by koalaman** [comment]
I'm actually increasingly leaning the other way. 

Right now I'm working on integrating shellcheck into a code review tool, and because SC1035 was reused both for the missing space in "[a = b]" and in "!false", where one has a significantly higher false positive rate than the other, I can't use it in a high precision whitelist.

It's annoying to have to block four warnings, but it's way easier than selectively blocking warnings that all have the same code.
