### ISSUE TITLE
SC2035 should suggest using --

### ISSUE THREAD

**Issue by dfong** [koalaman/shellcheck#548]
the SC2035 warning suggests using ./* instead of *, but in many cases i believe a better solution would be to insert "--".

consider a command like `tar cf whatever.tar *.conf` .  if we change the glob pattern to `./*.conf`, it affects the filenames stored in the tarball.  in a tar listing, the ./ would be present.

similarly, with a command like "ls *.conf", adding ./ would clutter up the listing, and possibly confuse commands downstream that many not expect ./ in the output.

i noticed that adding -- to the command line does silence the shellcheck warning.  i feel that this can be a better solution in the cases where the command in question honors "--".

**Comment by deryni** [comment]
The problem with `--` is that it isn't universal (across commands), or universally portable (between the same command from different sources). The `--` is, I believe, a GNU-ism and so isn't available with BSD-derived (or other) tools.

**Comment by dfong** [comment]
although i agree that support for "--" is not universal, i believe it is a posix standard (in the posix getopts).

plus, when i added "--" to the command line that shellcheck had been complaining about, the SC2035 warning went away.  this leads me to believe that shellcheck already has some special-casing for "--".


i would also note that there are other shellcheck warnings that make suggestions that are not universal.  for example, the one about using bash's `${var//}` notation instead of sed if possible.

in the case where it is possible to use "--", i feel it is a better solution.  because, unlike adding ./ to the glob pattern, adding "--" doesn't change the command's output in the usual case where there aren't any filenames starting with "-".

**Comment by deryni** [comment]
The suggestion to use `${var//}` happens in the context of a bash script where it is known that it will work. No such knowledge can be had about whether `--` will work for any given command (without a list and some attempts at guessing based on observed options).

Yes, `--` is POSIX for [`getopts`](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/getopts.html) but `getopts` is a specific mechanism.

Yes, `--` is a POSIX [Utility Syntax Guildeline](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02).

Neither of those things changes the fact that it isn't universal across commands or sources and that shellcheck can't know which do and which don't. It could certainly include `--` as an option as well as `./` though (which it does on the [SC2035 wiki page](https://github.com/koalaman/shellcheck/wiki/SC2035)).

I should point out, in case it wasn't clear, that I'm not responsible for shellcheck in any way. Just a user.

**Comment by dfong** [comment]
FYI, SC2001 warning/suggestion is made in context where it is NOT known that it will work.
the wording is:
^-- SC2001: See if you can use ${variable//search/replace} instead.

another example is the "possible misspelling" warning.

in fact, a lot of shellcheck warnings are issued in situations where following the suggestion might not be correct.  like, it is not always correct to double-quote a variable reference.

more to the point, it is also not always safe to add ./ to a glob pattern.  because, although it's the "same" file, the path to the file is different, and that can affect the behavior of the program.

**Comment by deryni** [comment]
I believe the "See if" in SC2001 is because the `//` pattern support is *not* a regular expression and so *cannot* do everything that `sed`/etc. can and without evaluating the specific pattern (and even then) shellcheck can't know whether you can replace one with the other. I do *not* believe it has anything to do with not knowing that `//` is valid. (And, in fact, in `#!/bin/sh` mode SC2001 does **not** fire for the example on the SC2001 wiki page.)

The "hesitation" in possible misspelling warnings about variable names are also **not** about whether the environment of the script itself can support the correction but about whether shellcheck correctly guessed the author's intent (something it can't know if it got right). Similarly with quoting variables. It isn't that shellcheck doesn't know whether quoting the variable is **valid** or not. It is that it doesn't know whether, for some reason, you want **this** specific variable usage unquoted (because you need globbing or word splitting). 

I cannot think of a situation in which adding `./` to a path would cause any programs to do anything incorrect with a file in the local directory but I can't say that none ever will either. You are certainly correct that in cases where `--` is possible it can be preferable (and is my personal preference as well). That doesn't change the fact that it simply isn't universally suitable and cannot be depended on to work for any given situation. Whereas prepending `./` *can* (barring ill-behaved programs that treat `file` and `./file` differently in some meaningful way).

**Comment by dfong** [comment]
the point is: the suggestions in these other examples i gave are also not universal.  they are not always applicable, and when they are applicable, they may not be correct.  when they are correct, the suggestions usually improve the quality of the code.  i believe the same applies to "--" when SC2001 is issued.

**Comment by kurahaupo** [comment]
On Mon, 16 Nov 2015, Etan Reisner wrote:
> I cannot think of a situation in which adding `./` to a path would cause any programs to do anything [different]

The most obvious case is commands; ./foo will run foo in the current
directory only, whereas foo will search $PATH, which usually does not
include the current directory.

Admittedly, one often wants the opposite: to use the filename directly
rather than searching $PATH. But there's a potential use case any time the
name of a file actually has semantics, rather than just being the means of
accessing the file's contents.

**Comment by deryni** [comment]
@kurahaupo That's not an argument to something else though generally, but true. If you are passing a name of a command to run later through an argument it can make a difference. But using a word that starts with a glob for that argument is a bit odd and nothing that doesn't start with a glob is at issue here.

**Comment by deryni** [comment]
@dfong I'm making a distinction between different types of suggestions in a way that I realize is a bit thin but I do think it is valid one. It is the difference between a suggestion for a change that shellcheck can't determine if you can actually make because it can't be certain it knows what you want to be doing and a suggestion for a change that shellcheck can't be certain is even *legal*.

And like I said SC2035 *does* mention `--` on the wiki page. Putting it in the shellcheck message isn't unreasonable it just may cause problems without appropriate caveats (the wiki should probably get those caveats about `--` also but at least it links to a good page on this topic).

**Comment by dfong** [comment]
i don't get the validity of this distinction.  it is always "legal" to add a -- to the command list.  it may not work they way you want.  the bottom line is the same as with ${var//} : you can always try it, but it may not work the way you want.  if you apply the same standard to "--", it is equally legal to add it to the command line of any command.  (it may fail.)

i'd also like to address this comment, ``Neither of those things changes the fact that it isn't universal across commands or sources and that shellcheck can't know which do and which don't.''

actually from what i've observed, shellcheck can and DOES know in specific cases.  in particular shellcheck has built-in knowledge about "ls".  some of shellcheck's warnings are specifically about ls.  and ls does support "--".

i think "try using --" is a better suggestion than "use ./" in general, but even moreso when the command is ls.

**Comment by koalaman** [comment]
I agree that mentioning `--` in the error isn't unreasonable, and 8ec87d6 does that.
