### ISSUE TITLE
Can this thing be wired up for Makefiles?

### ISSUE THREAD

**Issue by RhysU** [koalaman/shellcheck#58]
A buddy asked if there was some way to integrate the shellcheck goodness with an understanding of Makefile rule syntax.

**Comment by adius** [comment]
This would be so great! 😭

We have kind of a company policy to (almost) never write bash scripts,
cause most of the time you actually want a makefile.
But this means no shellcheck goodness for the shell scripts in the makefile rules ☹️.

**Comment by chadbrewbaker** [comment]
Bump. I really need this, even if just README documentation for setup.  Perhaps carve shellcode with https://github.com/mrtazz/checkmake and then apply shellcheck?

**Comment by austin987** [comment]
The maintainer has marked the bug as closed because it's outside of the scope of the project (https://github.com/koalaman/shellcheck/issues/58#issuecomment-32308163).

If you really want it, you'll likely need to either fork shellcheck or make your own project (potentially wrapping around shellcheck).

**Comment by chadbrewbaker** [comment]
I suggested adding a README/Doc that discussed *how to use shellcheck* on Makefiles, not adding direct Makefile support. Forking shellcheck to add docs is silly.

**Comment by chadbrewbaker** [comment]
Anyhow noodling on a solution that feeds make -n into shellcheck. Will submit a docs PR once I get it working.

**Comment by aparcar** [comment]
Any update on this?

**Comment by ottok** [comment]
You can run simply `make -n` in your project to see if Make itself spits out syntax errors.

For more deeper analysis there seems to exist https://github.com/mrtazz/checkmake

**Comment by mcandre** [comment]
This kind of support is desperately needed to detect subtle, critical flaws in very many scripts. Nobody is linting for quoting problems in the shell code in their makefiles. Or Jenkinsfiles. Or GitHub Actions. Or Kubernetes container entrypoints. And so on.

At present, the best the user can do is to be incredibly disciplined about moving ALL shell code into dedicated .sh files, and then executing those files from the outer programming language. To keep embedded shell code to a very simple, bare minimum. If you happen to write *and lint* tons of pure shell scripts yourself, ideally POSIX sh, then you will naturally develop strong, healthy habits over time, such as proper shell quoting techniques. For example, eshewing GNU and other non-portable command line flags in shell commands. But that kind of discipline is terribly rare in the wild.

Nobody in large scale projects seems to understand just how vulnerable this ecosystem is. I haven't found a single DevOps team that has ever bothered to lint their Dockerfiles in terms of Docker best practices, let alone lint their Dockerfiles' RUN/ENTRYPOINT commands shell commands. These little glue code snippets often get ignored, with all the safety and security problems that automatically arise from such negligence.

make itself has an incredibly small linter ecosystem, smaller than even shell's linter ecosystem. I have written an example makefile linter (in Rust), which is able to extract most of the shell commands from a POSIX compliant makefile's list of commands, in the form of a parsing AST. Then the individual commands could be plugged into a linter library such as ShellCheck.

https://github.com/mcandre/unmake

In theory, unmake could export the parser library as object files suitable for C FFI loading into ShellCheck's Haskell FFI bindings. Or someone could even rewrite ShellCheck in Rust. Regardless, our users deserve more defensive tools to catch the thousands of basic screwups that shell-adjacent coding tends to invite.

I have a lot of respect for the good work that ShellCheck has been doing to shore up shell scripts. I would very much like to see things like deeper zsh support, and makefile, and Dockerfile support as first tier features, without the ShellCheck user having to install yet more tools to accomplish safety. But even a reasonably constructed third party tool would go a long way toward building a more reliable Internet.

**Comment by mcandre** [comment]
Posted an example guide to writing a pure (POSIX) sh build system configuration.

https://github.com/mcandre/beltaloada

Purists may like something like that. I think for the sake of my contributor's cognitive load that I'll stick to make, and advise very short, mentally debuggable commands in makefiles.

**Comment by ottok** [comment]
As said, there is https://github.com/mrtazz/checkmake specifically for Makefiles. For Dockerfiles there is https://github.com/hadolint/hadolint. There is also tools like https://perldoc.perl.org/podchecker for podfiles. 

I don't know how much work it would be to extend ShellCheck to understand new file formats, but my intuition would be to prefer that the same project that owns the respective format (e.g. OCI for Containerfiles) would publish their own file specification and a linter that adheres to it. If is probably too much work for a 3rd party tool to catch up on file format changes in other projects unless there is a very strict and stable standard.

Another avenue would be to extend the editor plugins (e.g https://web.pulsar-edit.dev/packages/linter-shellcheck) to parse out shell invocations from other file types and feed only them to Shellcheck. This is how some spell checking (for human languages) plugins work when they extract English from code comments and UI strings from file types that are otherwise code files.

**Comment by mcandre** [comment]
mrtazz/checkmake is rather limited, why I took the liberty of publishing *unmake*.

hadolint has the luxury of being implemented in Haskell itself, so that it naturally hooks into the ShellCheck Haskell library.

But that is a rarity among linters, which (sad to say) tend to be implemented in Node.js or Python these days. A smattering in C++.

For these linters, it would help if ShellCheck generated C object files and published them to Conan. Then every other language could consume the library via FFI.

Or write temp files and shell out to the ShellCheck CLI, lol.
