### ISSUE TITLE
False positive SC2016 for sed scripts

### ISSUE THREAD

**Issue by arth1** [koalaman/shellcheck#584]
Consider this snippet (which copies everything after a marker, but not the marker itself):

sed -n <foo '/^#MARKER/,${/^#MARKER/d;p}'

This results in a SC2016: Expressions don't expand in single quotes, use double quotes for that.

Could ${ be excluded from sed scripts?

**Comment by koalaman** [comment]
`sed` is a tricky case because it's so commonly misused, but also uses `$` for many legitimate things. It's not optimal to just ignore `${` since this is a perfectly normal variable expansion. 7e75d12 fixes this particular case and a few others. 

I also updated the wiki to suggest more generous spacing (like `$ { /^#..`) as an alternative to having to ignore with a directive, which is always a hassle.
