### ISSUE TITLE
Incorrectly warns of if ((....)) construct

### ISSUE THREAD

**Issue by cvmiller** [koalaman/shellcheck#615]
When running the web version of shellcheck, it reports:
94  if (( $RESTORE == 1 )); then
            ^––SC2004 $/${} is unnecessary on arithmetic variables.

When using double parens in a conditional, it is doing an arithmetic comparison, not an arithmetic operation.

Therefore it should not warn this code.

**Comment by koalaman** [comment]
I'm not sure I understand. Why is this not better written as ` if (( RESTORE == 1 )); then`?

**Comment by kurahaupo** [comment]
Of course it should warn, because the $ sign is misleading.

In arithmetic context, comparisons ARE arithmetic operations; `a==b` is an
operation returning 0 or 1.

The arithmetic statement ((...)) behaves exactly the same regardless of
context; if by "conditional" you mean it is subordinate to "if", that is
irrelevant.

If RESTORE contains an arithmetic combination of bits, say, "2 | 1",
then using or not using $ changes the behaviour. The statement
(($RESTORE==1)) succeeds, while ((RESTORE==1)) fails.

**Comment by cvmiller** [comment]
Martin,

Good point. I can see by your example the $RESTORE is misleading.

thank you for the explanation.

Craig...

-- 
IPv6 is the future!
http://ipv6-net.blogspot.ca/
