### ISSUE TITLE
SC1037 should give a non-POSIX warning; also it's invalid for dash

### ISSUE THREAD

**Issue by Arthur2e5** [koalaman/shellcheck#621]
Per https://gnu.org/s/autoconf/manual/html_node/Shell-Substitutions.html, section '`${10}`':

* Any attempts to access positional params beyond `$9` is non-POSIX. This matches my memory of POSIX V3 Chap2, but I am too lazy to look at that now. May want to add SC2039 too.
* `dash` [wrongly](https://gnu.org/s/autoconf/manual/html_node/Shell-Substitutions.html) interprets `$10` as `${10}` by default (and there are no switches available). ~~Since it's a rather popular shell, and often thought to be a very POSIX one, perhaps it's good to warn about the non-deterministic-by-mistake property of the construct too.~~

(Yeah, autoconf 'portable shell scripting' is so damn good for showing how almost every shell sucks…)

**Comment by bittorf** [comment]
so a POSIX'ly correct workaround for accessing e.g. ${10} is IMHO:
```
#!/bin/sh
set -- 1 2 3 4 5 6 7 8 9 10 11
shift 9
echo $1  # outputs '10'
```
is this true?

**Comment by Arthur2e5** [comment]
Yes.

**Comment by koalaman** [comment]
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_05_01 says

>When a positional parameter with more than one digit is specified, the application shall enclose the digits in braces

**Comment by Arthur2e5** [comment]
Hmmmmmmmmmmmm.

**Comment by EliahKagan** [comment]
As [mentioned](https://github.com/koalaman/shellcheck/issues/621#issuecomment-194055788), POSIX supports expanding positional parameters past `9` (and has at least since [SUSv2](http://pubs.opengroup.org/onlinepubs/7990989775/xcu/chap2.html#tag_001_005_001)), so [I've removed](https://github.com/koalaman/shellcheck/wiki/SC1037/_compare/a46e8c0fde97716cf224d25df4bdb53b79c98ad5...454dfb5980960606da01e060cefcb3d6f547ba76) the "non-POSIX" note from the [SC1037 wiki page](https://github.com/koalaman/shellcheck/wiki/SC1037). I hope that's okay.
