### ISSUE TITLE
SC2069: 2>&1 does not always have to be last.

### ISSUE THREAD

**Issue by markgollnick** [koalaman/shellcheck#633]
###### Bug Description:
- shellcheck produces an error in cases of intentionally redirecting stderr to stdout _before_ redirecting stdout somewhere else (like `/dev/null`).
- shellcheck produces _nothing_ in cases where such a redirect occurs in a subshell. I am not sure if this is intentional or not.
###### Bug Reproduction:

`test.sh`:

``` bash
#!/bin/sh

squawk_out() {
  printf "out\n"
}

squawk_err() {
  1>&2 printf "err\n"
}

some_tool_that_squawks_on_both() {
  squawk_out  # Useless drivel
  squawk_err  # This stuff is actually interesting
}

example_one() {
  # Copy stdout file descriptor to stderr, then redirect stdout to /dev/null
  some_tool_that_squawks_on_both 2>&1 1>/dev/null
}

example_two() {
  data="$(some_tool_that_squawks_on_both 2>&1 1>/dev/null)"
  printf "%s\n" "$data"
}

main() {
  data1="$(example_one)"
  data2="$(example_two)"
  printf "data1: %s\ndata2: %s\n" "$data1" "$data2"
}

main
```

When run through bash in sh mode, the above script produces:

```
$ ./test.sh
data1: err
data2: err
```

**BUG:** When run through shellcheck, the `2>&1 >/dev/null` bit in `example_one` produces an error, whereas the same redirect in `example_two` produces nothing:

```
$ shellcheck test.sh

In test.sh line 17:
  some_tool_that_squawks_on_both 2>&1 1>/dev/null
                                 ^-- SC2069: The order of the 2>&1 and the redirect matters. The 2>&1 has to be last.
```

**EXPECTATION:** If I want to work around this error, I _could_ change every case of using `2>&1 1>…` to use the second form, but I think that if this behavior is a valid use-case of redirects, (I checked [POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_07) but could not find anything indicating that the shell behavior I’m seeing [and relying on in some cases] is invalid) then it should not be flagged an error at all, but rather as a warning (since putting them in this order _is_ a fairly common gotcha when the user’s goal is to redirect both stdout and stderr to the same destination). Additionally, I’m thinking that it should probably be flagged as a warning in both cases rather than just the one, if possible.
###### Environment/Versions:
- shellcheck v0.4.3

**Comment by koalaman** [comment]
Your use case is most definitely valid, it's just way less common than just getting it wrong. 

The only way for shellcheck to know if this is intentional is if it looks like you're using stdout for something, such as piping and capturing it. This was bug #260 and why you don't get an error in `$(..)`.

One could certainly make a convincing argument that this should be a warning instead of an error though. 

The reason why it's currently an error is that sh is an incredibly....flexible language. For example, `[ 1 < 2 ]` is a perfectly valid and POSIX compatible replacement for `[ -r 2 ]`, checking if there's a readable file called "2" in the current directory. You probably wouldn't expect that, but it's also not wrong. Therefore, ShellCheck pragmatically uses the error code as a triage for things you should look at first rather than as a classifier of errors that simply have no chance of working.

**Comment by scottleibrand** [comment]
:+1: for making this a warning instead of an error, and/or checking if you're using stdout for something, such as piping.  I'm using the `2>&1 >/dev/null | tail -1` syntax on purpose to redirect stderr to tail, and stdout to /dev/null, but shellcheck doesn't like that at all.

**Comment by koalaman** [comment]
This is now a warning, and an earlier fix made it not trigger when the output is captured or piped. Thanks!
