### ISSUE TITLE
Parse error when being creative with else if instead of elif.

### ISSUE THREAD

**Issue by knirch** [koalaman/shellcheck#671]
(sorry for this)

Someone ran shellcheck on bk.sh (https://raw.githubusercontent.com/bitkeeper-scm/bitkeeper/master/src/bk.sh) and found this gem:

```bash
_ignore() {
        if [ "x$1" = x ]
        then    if [ -f BitKeeper/etc/ignore ]
                then    cat BitKeeper/etc/ignore
                else    if bk _test -f BitKeeper/etc/SCCS/s.ignore
                        then    bk get -sp BitKeeper/etc/ignore
                        fi
                fi
        fi
}
```

It's simple enough to fix the code by collapsing that else if to an elif. Just thought I'd show it.(And the creative indentation)

**Comment by brother** [comment]
Do remember that "else ... if" is not the same as "elif".

**Comment by koalaman** [comment]
ShellCheck currently intentionally parse `else if` as if you had written `elif`.

Pro: It keeps parsing code where people think that's ok, giving more useful tips.
Con: It fails parsing code that uses `else if` in an entirely valid way like this example, and failing on valid code is never a good thing.

I went over a small corpus of shell scripts gathered from #bash@freenode and found:
* 10 scripts where parsing `else if` as `elif` was the right call.
* 2 scripts where parsing `else if` as `else if` was the right call.
* 4 scripts where I had no idea what the user intended.

Obviously,  these scripts are diseased in the first place, which is why people posted them, so there's a serious bias. 

I really hate to misparse valid scripts, but in this case I think it's better for overall quality to leave the current behavior. I updated the message in 6dc419b to suggest putting the `if` on a separate line if nesting if statements.

If anyone can provide better data, please reopen this bug and I'll change the behavior.
