### ISSUE TITLE
Possible 'Bourneism' info notification for using ! and /bin/sh.

### ISSUE THREAD

**Issue by rawiriblundell** [koalaman/shellcheck#692]
I've found an odd behaviour while coding a mostly portable script: sometimes on Solaris 10 and older, "!" doesn't work.

For example `if [ ! -d /some/path ]; then` will break.  And sometimes it won't.  And sometimes again it will.  I can't track down which factors actually determine the failure.

On a Solaris 10 host, for example, we can see that '!' is something `/bin/sh` isn't happy with:

```
$ type [ !
[ is a shell builtin
! not found
```

On Solaris 11, /bin/sh links to ksh93, so no problem:

```
$ type [ !
[ is a shell builtin  
! is a shell keyword
```

The interesting thing is that `type` may say it's not found, but as I said, sometimes it will still work e.g.

```
$ if [ ! -d /blargh ]; then echo "not found"; fi
not found
```

The fix I settled on to make it work reliably was to use `:` as a dummy/no-op action:

```
if [ -d /blargh ]; then
  :
else
  echo "not found"
fi
```

`true` may also be acceptable under POSIX, and more readable to boot, but IIRC, `:` predates `true`, so is probably the better option to recommend.  If we're assuming a reversion towards The Bourne Way (tm)

So that's perhaps something to throw an info link on if the shebang is `#!/bin/sh`?

You can see an example of this behaviour (that I've just found to confirm that I'm not going crazy) here:

https://github.com/jordansissel/fpm/issues/129

**Comment by kurahaupo** [comment]
You could just use ```! [ ... ]``` instead of ```[ ! ... ]```

**Comment by rawiriblundell** [comment]
When the issue experienced is that `!` is not reliably found, then your solution is also not going to be reliable.  If you look at the reference link I supplied, you'll notice that your proposed idiom is used - and fails - there too.  So do `if ! program >/dev/null` style tests.  And just to confirm that, using `/bin/sh` on a Solaris 10 box I have handy:

```
$ type !
! not found
$ if ! command -v pants; then echo "blah"; fi
!: not found
$ if ! [ -d /path/to/pants ]; then echo "something"; fi
!: not found
```

p.s. Great to see a fellow Kiwi using shellcheck!

**Comment by geirha** [comment]
`/bin/sh` on Solaris 10 is the bourne shell. On more or less every other UNIX and UNIX-like system, including Solaris 11, `/bin/sh` is a POSIX shell, and it's POSIX shell features that shellcheck checks for when the shebang is `#!/bin/sh`. POSIX defines that sh should have a `!` to negate a command's exit status, and that the `test` command should have a `!` operator to negate the following expression's truth value.

In bourne you have to use the `else` part of if instead:

```
# POSIX:
if ! cmd; then
    printf 'Command failed\n'
fi

# Bourne:
if cmd
then
    :
else
    echo "Command failed"
fi
``` 

So the issue is really: should Shellcheck support the bourne shell in addition to the shells it already support?

Bourne is a dying shell. It's mostly just older solaris systems that keep it alive outside a museum these days. Sounds like a waste of time to me to write support for a dying shell.

**Comment by rawiriblundell** [comment]
You have a good point... but then again, I often do agree with you http://i.imgur.com/8cLeHF0.png :)

**Comment by kurahaupo** [comment]
If you might meet a shell that lacks a built-in `!` it may suffice to define it as a function:
```
type ! > /dev/null 2>&1 || eval '
! () {
  if "$@"
  then return 1
  else return 0
  fi
}'
```
Of course this assumes that said shell has functions and isn't too strict about their names. And that you don't want to use `!` on compound statements, though you might get around that by applying de Morgan's transformations.
