### ISSUE TITLE
aliases with embedded awk are treated as aliases with arguments

### ISSUE THREAD

**Issue by anishsane** [koalaman/shellcheck#728]
Consider this case

    alias cut_first="awk '{print \$1}'"

Here, shellcheck is unable to understand that the `$1` used here is internal to `awk`. It thinks that we are defining an alias with arguments / positional parameters. Thus, suggests use of a function instead (SC2142).

	$ shellcheck myscript
	 
	Line 1:
	alias cut_first="awk '{print \$1}'"
		  ^-- SC2142: Aliases can't use positional parameters. Use a function.
	$ 

Now, this is a perfectly legit code as far as aliases are concerned.
Please try to fix this.

**Comment by kurahaupo** [comment]
> alias cut_first="awk '{print \$1}'"

The mere face that Shellcheck has misdiagnosed the exact nature of the
problem, is itself a reason to heed the suggestion; using a function sounds
like a good idea anyway given the complexity of multiple levels of quoting
and escaping.

Using a function is longer than an alias by 3 characters (for including
"$@") but the resulting code is clearer:

> cut_first() { awk '{print $1}' "$@"; }

I would like to see a warning any time an alias uses nested quotes or
backslashes on quotes or dollar signs, to suggest using a function instead.

PS: I never use aliases if I can help it; in fact my personal ~/.bashrc has
this line near the top:

> alias() {

to define a function so that attempts by /etc/bash* to define aliases will
actually define equivalent functions instead. (The function is actually
about 50 lines, to make allowances for corner cases, so I won't paste the
whole thing here.)

**Comment by koalaman** [comment]
I agree with @kurahaupo. eval-like code indirection like aliases is iffy in general, and if it wasn't for immediately recognizing the `awk '{ print` pattern, I might have thought it was an invalid attempt too.

It's always regrettable to give false positives, but in this edge case it's better to rewrite it as a function anyways. I've updated the wiki to include this case.
