### ISSUE TITLE
Expose goodShells so external tools can use it.

### ISSUE THREAD

**Issue by acook** [koalaman/shellcheck#737]
ShellCheck validates scripts in a couple of different ways, but pivotally uses [`goodShells`](https://github.com/koalaman/shellcheck/blob/13a2070a323eab98ef54b78b22ae4c33d66d4084/ShellCheck/Parser.hs#L2593) to check against script types.

We've duplicated this list in [CodeClimate's ShellCheck engine](https://github.com/filib/codeclimate-shellcheck) in [this file](https://github.com/filib/codeclimate-shellcheck/blob/master/src/CC/ShellCheck/ShellScript.hs#L27) but we'd prefer to use the upstream version so we can remain in sync.

Purpose: We're using this list to check file extensions (as is best-practice for non-portable shell scripts) so we can make sure to send ShellCheck only receives a subset of files instead of having to vet every file in an entire repo.

**Comment by kurahaupo** [comment]
On Sun, 25 Sep 2016, Anthony M. Cook wrote:
> Purpose: We're using this list to check file extensions (as is
> best-practice for non-portable shell scripts) [...]

If anything this seems *contrary* to best practice ...

Best practice is that suffixes should be entirely avoided for any program --
script or otherwise -- that is installed in a "bin" directory, and thus is
reachable via PATH rather than its full pathname. To do otherwise breaks the
principle of substitutability.

Which means that the appropriate check is to look at the basename of the
shebang line, and only fall back to the extension if there is none.

**Comment by acook** [comment]
It isn't for programs in `bin`, no mention of `bin` was made. This was explicitly stated to be for repositories that use CodeClimate and embed scripts. They might be build scripts or test scripts for CI or for bash configurations or many many other uses for scripts which do not reside in the system bin path.

**Comment by filib** [comment]
@kurahaupo `codeclimate-shellcheck` takes the following approach:

- If the script has a valid file extension, submit it to ShellCheck for analysis.
- Else, check the shebang.

I'm totally open to how this could be improved and if you'd like to submit a pull request, please do so. The code is [here](https://github.com/filib/codeclimate-shellcheck/blob/master/src/CC/ShellCheck/ShellScript.hs#L58-L66).

As for @acook's request, we were only hoping to be a bit more in sync with ShellCheck rather than maintain our own list of good shells, which would be useful to use since we're using ShellCheck as a library.

**Comment by filib** [comment]
@koalaman would you accept a patch along these lines? I'm happy to prepare it but it's fine if you don't think it would fit.

**Comment by koalaman** [comment]
I don't think exposing this list on a Haskell level would be a great solution. This part of the code is already in need of a rewrite (logic is partially duplicated in the analysis part). It's also not just a list of recognized shells, it's matched by prefix due to things like `ksh93`. It also already fails for `#!/bin/busybox.static sh`.

How about an exposed function that accepts a filename and returns since indication that the file could be shellchecked?

**Comment by filib** [comment]
> How about an exposed function that accepts a filename and returns since indication that the file could be shellchecked?

That'd be ideal! Would you like any help implementing that? Appreciate you may be busy.

**Comment by koalaman** [comment]
That would be great! 

* What should the type be? Just `FilePath -> Boolean` to recognize a probable script or `FilePath -> Maybe Shell`  to identify the shell?
* What should the implementation do? Look for `.sh` or similar extension, and otherwise look for a shebang?
* How can shellcheck itself make use this functionality? Maybe a `--scripts-only` type flag that lets you run `shellcheck --scripts-only foo.sh foo.c foo.o` and have non-scripts automatically ignored.

**Comment by kurahaupo** [comment]
On Sat, 15 Oct 2016, koalaman wrote:
> * What should the implementation do? Look for `.sh` or similar extension, and otherwise look for a shebang?

Please no, can we have that the other way around: shebang first, file suffix
second.

**Comment by filib** [comment]
@kurahaupo it sounds like you know something I don't. Can you say a little about the reasons why you'd choose to do it in this way or link to other projects that take the same approach?

**Comment by kurahaupo** [comment]
For me the braces are a signal that something *other* than a simple variable
expansion is involved. Consequently code that *always* use them is just that
bit harder to read as I can't skim-read based on that signal.

When I read
```
 somecmd  "$foo.bar"
```
it is completely obvious that "foo" is the variable name, whereas if I read
```
 somecmd "${some_long_variable_name}.bar"
```
then the initial "${" primes me to pay more attention because it will be
something more complex than a simple variable. (It is vaguely irritating my
effort to pay extra attention is wasted.)

(And if you think "what difference does it make to skim reading", consider
when you go looking for places where a variable is *modified*; one way that
can happen is with the ${var:=default} expansion; so looking closely at
brace-enclosed expansions is important.)

The notion that braces should always be used "for consistency" is IMO
flawed. Simple expansions usually outnumber complex ones by an considerable
margin, so you're changing the majority of the code to fit with the
minority; that's just backwards.

It makes the code longer and noisier.

It does not "resolve ambiguity" because there is no ambiguity. (In the
vanishingly small proportion of cases where you do need to delimit the
variable name from following alphanumeric characters, braces are OK, but
there are other options including quotes.)

It kills the utility of the "here be dragons" signal.

Readers will always have to cope with both, and if they deal with any other
programming language, the "pay extra attention" signal is lost if it's
over-used.

-Martin

**Comment by acook** [comment]
Closing this as copy and pasting seems a simpler solution since the list of shells is unlikely to change much.
