### ISSUE TITLE
Can't disable SC2086 when on an elif branch

### ISSUE THREAD

**Issue by austin987** [koalaman/shellcheck#744]
First off, thanks for shellcheck, it's a wonderful tool. I'm using it to cleanup / add regression tests to winetricks, and have noticed an issue. The code block it is complaining about is:
    echo "Installing $command"
    if [ "$EXPECT_FAIL" = "yes" ]
    then
        echo blah
    # FAILS HERE
    elif ! w_time sh winetricks --no-isolate -q nocrashdialog $command
    then
        echo do stuff
    else
        echo stuff
    fi

With no exclusions, I get:
In winetricks-test line 283:
    elif ! w_time sh winetricks --no-isolate -q nocrashdialog $command
                                                              ^-- SC2086: Double quote to prevent globbing and word splitting.

If I try to ignore that error by adding '# shellcheck disable=SC2086' above the elif (indented to the same level), I get:
austin@austin2:~/src/winetricks/tests$ shellcheck -s sh winetricks-test 

In winetricks-test line 277:
    if [ "$EXPECT_FAIL" = "yes" ]
    ^-- SC1009: The mentioned parser error was in this if expression.

In winetricks-test line 278:
    then
    ^-- SC1073: Couldn't parse this then clause.

In winetricks-test line 284:
    elif ! w_time sh winetricks --no-isolate -q nocrashdialog $command
         ^-- SC1072: Unexpected keyword/token. Fix any mentioned problems and try again.

austin@austin2:~/src/winetricks/tests$ shellcheck -V
ShellCheck - shell script analysis tool
version: 0.4.4
license: GNU General Public License, version 3
website: http://www.shellcheck.net

source is available at https://github.com/winetricks/winetricks fwiw

**Comment by koalaman** [comment]
That is indeed tricky. It happens because shellcheck directives are per complete command/structure, and not per line. Since `elif` is not a (complete) command, you can't put directives on it. 

Perhaps the best way forward would be to fix the issue that shellcheck complains about. 

In [the function in question](https://github.com/Winetricks/winetricks/blob/master/tests/winetricks-test#L261) there's a line `command="$*"` that defines the variable that is then used unquoted. This would join and split the string, thereby ruining the original spacing (causing it to fail on filenames with spaces), and may additionally fail on anything containing glob characters.

This would not happen if you used `"$@"` instead of `$command`, but I don't know if any of the other code depends on the current buggy behavior.

Anyways, if you just want to ignore this issue, what you can do is to put it after the elif and before the condition, which unfortunately makes formatting a bit weird:

```
if [ "$EXPECT_FAIL" = "yes" ]
then
echo blah

elif #shellcheck disable=2068
      ! w_time sh winetricks --no-isolate -q nocrashdialog $command
then
echo do stuff
else
echo stuff
fi
```

Or you can disable it for the entire `if` statement:

```
#shellcheck disable=2068
if [ "$EXPECT_FAIL" = "yes" ]
then
echo blah
elif ! w_time sh winetricks --no-isolate -q nocrashdialog $command
then
echo do stuff
else
echo stuff
fi
```

**Comment by austin987** [comment]
Okay, thanks @koalaman
