### ISSUE TITLE
Style: Add optional directive to flag for variable names not surrounded in curly braces

### ISSUE THREAD

**Issue by srcshelton** [koalaman/shellcheck#752]
IMHO, `${variable}` more clearly denotes that a string is a variable than simply `$variable`, and makes scripts more consistent when then using features such as `${isthisset:-}` or `${firstletter:0:1}`.

Could use of variables without braces be added as a default-off directive for code-style?

**Comment by kurahaupo** [comment]
On Fri, 21 Oct 2016, Stuart Shelton wrote:
> IMHO, `${variable}` more clearly denotes that a string is a variable than simply `$variable`, and makes scripts more consistent when then using features such as `${isthisset:-}` or `${firstletter:0:1}`.
>
> Could use of variables without braces be added as a default-off directive for code-style?

IMHO those extra braces are ugly, noisy, redundant, and cloud readability.
Your opinion is not universally shared.

Whether something is "easier" to read depends entirely on one's linguistic
background. For many of us the braces -- when NOT making substitutions --
are annoying noise that we would prefer not to see.

For those of us who started programming in C or C++ or Java or Perl or
Python, the boundaries of variable names are completely self-evident, so
extra delimiters serve no benefit.

There's a famous quote "consistency is the hobgoblin of small minds". For
those of us accustomed to scripts without extra braces, the presence of an
opening serves as a warning for "expect a complex expansion", which is then
an annoying distraction when no such complex expansion is actually present.

And then there's the tendency among newbies to assume that ${foo} is
equivalent to "$foo", which leads them to write functionally worse code when
they're told that they must use ${foo}.

-Martin

**Comment by srcshelton** [comment]
Sure - I think we can agree to disagree on this ;)

Should our disagreement preclude this being made an option for any who may find it useful, though?  I did suggest that this should be an opt-in directive, which should not enabled by default.  This approach appears to do very little harm: it provides everyone with the freedom to validate as they wish.

Perhaps an accompanying feature-addition would be to flag as a warning any use of braces around a variable which isn't strictly necessary, therefore also also meeting your expectations in terms of coding style?

"The nice thing about standards is that there are so many to choose from" - Andrew S. Tannenbaum

**Comment by marcjay** [comment]
To add another datapoint to this, Google's style guide prefers braces: https://google.github.io/styleguide/shell.xml?showone=Variable_expansion#Variable_expansion

> Don't brace-quote single character shell specials / positional parameters, unless strictly necessary or avoiding deep confusion. 
**Prefer brace-quoting all other variables.**

It's definitely something I'd like to see added, appreciate that it's a preference, like Google

**Comment by nhed** [comment]
@kurahaupo 
> For those of us who started programming in C or C++ or Java or Perl or
> Python, the boundaries of variable names are completely self-evident, so
> extra delimiters serve no benefit.

I too programmed in C/C++ before doing anything half serious in bash and you just happen to be wrong

```
function bergify {
    while [ ${#} -gt 0 ]; do
        local var="${1}"
        echo "${var}berg"
        echo "$varberg"
        shift
    done
}

bergify bloom rosen gold
```

In C you do not have variable expansion in the middle of a literal - in the above `bergify` you can see how the ambiguity comes to bite back, this would have worked if there was a space between `$var` and `berg` but changing your reference just on the presence of neighboring characters is silly.

**Comment by kurahaupo** [comment]
@nhed 

> ```
>         echo "${var}berg"
>         echo "$varberg"
> ```

> you can see how the ambiguity comes to bite back,

On the contrary, this illustrates my point perfectly: *there is no ambiguity*. It is glaringly obvious that the second line mistakenly refers to a variable called "varberg".

> changing your reference just on the presence of neighboring characters is silly.

The Shell is chock full of inherent silliness already. "Silly" is just a pejorative term for "unexpected".

But if adding or removing the braces based on changes to the following characters bothers you that much, consider using separate quotes around the variable expansions; pick one of:

```
echo "$var""berg"
echo "$var"'berg'
echo "$var"berg
```

**Comment by kurahaupo** [comment]
> Sure - I think we can agree to disagree on this ;)
> 
> Should our disagreement preclude this being made an option for any who may find it useful, though?  I did suggest that this should be an opt-in directive, which should not enabled by default.  This approach appears to do very little harm: it provides everyone with the freedom to validate as they wish.
> 
> Perhaps an accompanying feature-addition would be to flag as a warning any use of braces around a variable which isn't strictly necessary, therefore also also meeting your expectations in terms of coding style?

I agree, and I would be happy to see both of these options added; I would be concerned if only one were added.

I've wondered about making git post-checkout & pre-commit hooks that automatically add & remove braces; then we can both be happy editing the same code in our own preferred styles. Unfortunately such a tool could easily become confused by complex writing, so I'd like to use Shellcheck to tell me when it's (un)safe to perform such transformations.

To that end, I would need a new default-off warning about apparent expansions inside nested quotes.

**Comment by nhed** [comment]
@kurahaupo  
> ```
> echo "$var""berg"
> echo "$var"'berg'
> echo "$var"berg
> ```
I can't see how this quote salad is better than braces, the only time you would catch me doing something like that is if i'm building up some `sed` expression with quotes.

but as OP suggested - maybe this should be on a per user/config basis if a developer or a team decides on a style they should be able to configure the linter for their agreed style.

**Comment by AlexSkrypnyk** [comment]
These opinions on whether there should or should not be curly braces around variables are moot.

This issues is about providing an option to highlight such cases. Let people decide themselves how they want to write their scripts.

**Comment by AlexSkrypnyk** [comment]
it is weird that neither shellcheck, nor shfmt or shellharden provide this option - tool author's decide for tool users how they have to write their scripts!

**Comment by dirtyharrycallahan** [comment]
I don't have an opinion but I will comment on the misused and misunderstood quote.

It is often even misquoted as simply "consistency is the hobgoblin of little minds" (or even more sloppy approximations like "conformity is a bugbear of small-minded people", etc.).

Here's the quotation in longer form, with more of its original context. It becomes immediately apparent that it has nothing to do with writing style, and everything to do with inflexible mentality:

A foolish consistency is the hobgoblin of little minds, adored by little statesmen and philosophers and divines. With consistency a great soul has simply nothing to do. He may as well concern himself with his shadow on the wall. Speak what you think now in hard words, and to-morrow speak what to-morrow thinks in hard words again, though it contradict every thing you said to-day. — 'Ah, so you shall be sure to be misunderstood.' — Is it so bad, then, to be misunderstood? Pythagoras was misunderstood, and Socrates, and Jesus, and Luther, and Copernicus, and Galileo, and Newton, and every pure and wise spirit that ever took flesh. To be great is to be misunderstood.
— Ralph Waldo Emerson, "[Self-Reliance](https://en.wikipedia.org/wiki/Self-Reliance)", [Essays: First Series](https://www.gutenberg.org/files/16643/16643-h/16643-h.htm#SELF-RELIANCE), 1841

Most people who quote or misquote the famous part of this passage do so to criticize an argument for textual, stylistic, or other presentational consistency, and are usually doing so to advance some alternative style in a mentally inflexible way. In doing so, they're foolishly displaying an ironic ignorance of Emerson's actual meaning and intent, which was criticism of refusal to change one's mind or adjust one's position in light of new facts or different situations.

https://en.wikipedia.org/wiki/Wikipedia:Emerson_and_Wilde_on_consistency

**Comment by Frenzie** [comment]
> Emerson was a professional writer, with a consistent style, and he was entirely used to formal writing that followed strict conventions (stricter then than today), and without difficulty complying with the house style of whatever publication he was writing for.

Is that based on an analysis of his own manuscripts? Plenty of authors object to inflexible editors changing all manner of stylistic, grammatical and vocabulary choices. If that statement is based on printed works it's meaningless by definition. Moreover, being able to do something doesn't imply liking it. The argument as presented does not provide any evidence for Emerson's opinions on matters of style. The failed attempt to do so is a red herring from the actual point, namely that the quotation doesn't refer to style in the first place.

**Comment by AlexSkrypnyk** [comment]
So I came up with this https://github.com/AlexSkrypnyk/shell-var-lint until this is is resolved

**Comment by port19x** [comment]
Doesn't [SC2250](https://www.shellcheck.net/wiki/SC2250) cover this?

**Comment by port19x** [comment]
> it is weird that neither shellcheck, nor shfmt or shellharden provide this option - tool author's decide for tool users how they have to write their scripts!

Imho this rule, as it is largely stylistic, belongs into shfmt.
Cases where the curly braces carry semantic meaning are covered by SC2250.
Otherwise true quoting using the `"` character is preferred for good reason.

**Comment by kurahaupo** [comment]
@srcshelton yes we can agree to disagree; we have diametrically opposed views on what is, at root, æsthetic preference born from our respective individual life experiences. Neither affects the correctness of a script.

@port19x I agree, ShellCheck should focus on correctness, and target issues that lead directly or indirectly to malfunctioning scripts. Æsthetic choices (like indentation or brace insertion/removal, or anything else that that can be automatically "repaired") more properly belong to shfmt.

Arguably the "VARCAP" rule is primarily an æsthetic choice, but it's in no-man's-land: shfmt cannot know whether the names of variables are significant outside the script itself, which leaves it to ShellCheck to offer advice on changing them.

---

@dirtyharrycallahan I'm aware that Emerson was critiquing mental inflexibility, so I'm twisting it a little - but not much.

I will criticize the use of "consistency" as the primary justification for a particular choice being "better", whenever that choice has made something else _less_ consistent (i.e. it's a disingenuous assertion), or whenever there's a consequent reduction in semantic redundancy (and thus impaired error correction).

This isn't about personal inflexibility on either side; I can and will write code however the house style dictates, even if I think it's ugly and harder to read, and I'm sure the proponents of such styles have similar flexibility. (There are a few very strange styles that I can barely read, much less write, but that's a self-sealing problem.)

---

Regarding Google, perhaps the most important thing in Google's house style for shell scripts is that anything longer than ~10 lines should not _be_ a shell script: it should be written in a different language. Their policy is to discourage writing new shell scripts, and to the extent that that's not possible, the aim of their Shell style guide is to make short scripts that read as if they were some other "more familiar" language.

This is a double-edged sword: anyone can easily read such a script, but they acquire (and keep) a flawed mental model of how the shell actually works, leading to the situation where, due to the author's unfamiliarity with the language, about 1% of _approved_ shell-related Piper commits _introduced_ bugs. Some significant portion of those were blind `s/plaintext/$variable/g` replacements, so in that context "always use braces" makes perfect sense.

Google's shell scripting guide does have a lot of good stuff in it, but it should not be taken wholesale as the basis for a general purpose guide intended to cover large or complex scripts; rather, such a guide should selectively choose items from Google's guide on an opt-in rather than opt-out basis.

**Comment by koalaman** [comment]
This optional check has since been added and can be enabled in e.g. `.shellcheckrc` with `enable=require-variable-braces`

**Comment by kurahaupo** [comment]
@koalaman Any chance we can have the reverse option: `enable=forbid-optional-braces` that complains if a simple variable is enclosed in braces and not followed by an alphanumeric?

**Comment by TinCanTech** [comment]
I think you need to enable cookies for the full spellcheck effect.

**Comment by wileyhy** [comment]
It's always nice to have style. :-)
