### ISSUE TITLE
Warning about egrep/fgrep being deprecated

### ISSUE THREAD

**Issue by facutuesca** [koalaman/shellcheck#811]
Currently, egrep and fgrep are deprecated, but most distributions provide them as aliases for grep to allow historical applications that rely on them to run unmodified [1]. Maybe a new rule could be added that warns the user about this, and suggest the equivalent use of grep

[1] http://manpages.ubuntu.com/manpages/precise/man1/grep.1.html

**Comment by koalaman** [comment]
Neat, didn't know that. Suggestions have been added in e679ff

**Comment by kurahaupo** [comment]
I'd like to suggest recommending against using -P too, as PCRE doesn't have
the "regular" (ie linear) performance that was originally meant by "regular
expression". Indeed PCRE has some awful worst-case performance issues,
and very few
searches actually *need* it.

(Anyone remember Facebook having an outage because someone posted an entry
with like a megabyte of trailing whitespace, which conspired with a naïve
"trim whitespace" function that used PCRE in a way that took quadratic
time?)

**Comment by koalaman** [comment]
I wouldn't be surprised, and it wouldn't be the first major regex related outage I've heard of.

However, it's sadly not PCRE specific:

```
$ time grep '^\(.*\)\1*$' <<< "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
aaaaaaaaaaaaaaaaaaaaaaaaaaaaa

real    0m32.180s
user    0m31.948s
sys     0m0.084s
```
