### ISSUE TITLE
Possible F/P — SC2086 vs setting default value

### ISSUE THREAD

**Issue by kgadek** [koalaman/shellcheck#826]
```sh
#!/bin/bash

: ${FOO:=123}
```

Both on shellcheck 0.4.5 and online the result is:

```
Line 3:
: ${FOO:=123}
  ^-- SC2086: Double quote to prevent globbing and word splitting.
```

I believe this is the proper way to set defaults and there is no issue here.

**Comment by koalaman** [comment]
ShellCheck is technically correct. You should quote this due to several weird edge cases. 

Try `export FOO='/*/*/*/*/*/*'` before running that script, and you'll see it trashing the disk for several minutes for no good reason. You can also make it gobble up arbitrary amounts of memory this way.

See #480 for more cases that apply to this construct in general, but not in this particular toy script.
