### ISSUE TITLE
shellcheck disable directives doesnt work in the scope of a function

### ISSUE THREAD

**Issue by ccztux** [koalaman/shellcheck#857]
#### For bugs
- SC1001, SC2154
- Latest docker image: 0.4.5
- [x ] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ ] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### Here's a snippet or screenshot that shows the problem with SC2154:

```bash
#!/usr/bin/env bash

removeFile()
{
        # shellcheck disable=SC2154
        local file="$1"
        ${rm_bin} "$file"
}


removeFile "/home/pi/test_file.txt"
```

#### Here's what shellcheck currently says:

Line 9:
        ${rm_bin} "$file"
        ^-- SC2154: rm_bin is referenced but not assigned.

#### Here's what I wanted or expected to see:

No issues detected!

#### Here's a snippet or screenshot that shows the problem with SC1001:

```bash
#!/usr/bin/env bash


checkTrailingSlash()
{
        #shellcheck disable=SC1001
        
        local path="${1:-}"

        if [[ "${path}" =~ ^(.*)\/$ ]] ;then
                return 1
        else
                return 0
        fi
}

checkTrailingSlash "/home/pi/"
```

#### Here's what shellcheck currently says:

Line 11:
        if [[ "${path}" =~ ^(.*)\/$ ]] ;then
                                ^-- SC1001: This \/ will be a regular '/' in this context.

#### Here's what I wanted or expected to see:

No issues detected!

[I use shellcheck in conjunction with travis ci using the latest docker image.](https://travis-ci.org/ccztux/glsysbackup/builds/215191503)

It works, if i put both shellcheck disable directives to the top of the script, but not, if it put the directives in the affected functions.

**Comment by koalaman** [comment]
Directives actually apply to the command or structure they're placed in front of, and not the command list they're a part of.

In this case you can apply it to the whole function:

```
# shellcheck disable=SC2154
removeFile()
{
        local file="$1"
        ${rm_bin} "$file"
}
```

Or just the particular command:
```
removeFile()
{
        local file="$1"
        # shellcheck disable=SC2154
        ${rm_bin} "$file"
}
```

Directives at the start of the file are the exception, and will indeed apply to the whole script and not just the next command. I see how that's inconsistent and confusing.

**Comment by ccztux** [comment]
Thank you for clarifying this!

**Comment by kurahaupo** [comment]
Have more trust in Shellcheck; it tells you these things for a reason.

> removeFile()
> {
>         # shellcheck disable=SC2154
>         local file="$1"
>         ${rm_bin} "$file"
> }

One of the nice uses for shell functions is to *entirely avoid* using variables in contexts like this; rather, simple define the function in different ways depending on what behaviour you want to select, for example:

    if [[ -x /path/to/MySpecialRm ]] ; then
        removeFile() { /path/to/MySpecialRm "$@" ; }
    else
        removeFile() { /bin/rm -f "$@" ; }  # POSIX says `rm` has to be here
    fi

(I can't tell from the given code, but there is no point writing `rm_bin=$(which rm) ; ${rm_bin}` because that has the same effect as just writing `rm`, only slower.)

> checkTrailingSlash()
> {
>         #shellcheck disable=SC1001
>
>         local path="${1:-}"
>
>         if [[ "${path}" =~ ^(.*)\/$ ]] ;then
>                 return 1
>         else
>                 return 0
>         fi
> }

Slash has never been special to regex; and while it is special to some of the languages which embed regex, Bash is not one of those languages. So rather than disabling SC1001, I would recommend simply following its suggestion and removing the unnecessary backslash before the slash, thus:

    checkTrailingSlash() { [[ ${1:-} !~ ^(.*)/$ ]]
        local path="${1:-}"

        if [[ "${path}" =~ ^(.*)/$ ]] ;then
                return 1
        else
                return 0
        fi
    }

And then I would simplify that to:

    checkTrailingSlash() {
        [[ ${1:-} !~ ^(.*)/$ ]]
    }

And then (assuming you're not examining REMATCH) I'd simplify that even further, to:

    checkTrailingSlash() {
        [[ ${1:-} !~ /$ ]]
    }

But I'd do away with regex entirely and just use a glob:

    checkTrailingSlash() {
        [[ ${1:-} != */ ]]
    }

At which point I'd wonder why I was writing a function at all?

**Comment by ccztux** [comment]
Hi!

Thank you for your repy. In the meantime i have deleted the function checkTrailingSlash. The function removeFile was only a suitable example and i dont use it in any script. Anyway, thank you for pointing this out.
