### ISSUE TITLE
doco issue with docker and  'openBinaryFile: does not exist' error 

### ISSUE THREAD

**Issue by client9** [koalaman/shellcheck#911]
First: wow, such a great project.

I bumped into a doco or user-error bug when using the docker image

Explicit filenames work great:

```
docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/myscript.sh
# yay no errors
```

But variations using shell wildcard  (glob) are not  /scripts/*.sh
```
docker run -v $(pwd):/scripts koalaman/shellcheck '/scripts/*.sh'
/scripts/*.sh: /scripts/*.sh: openBinaryFile: does not exist (No such file or directory)
```

Not the end of the world but not what I expected and probably could be better error message.

Or is there an equiv in haskel for '*' ?

regards,

nickg

**Comment by koalaman** [comment]
Very relevant question. The docker instructions suggested mounting the current working dir as `/scripts` and then checking scripts there. This means that globs don't work, because they're expanded before Docker is invoked (kudos to Docker for not trying to "make it work" by re-expanding input). 

If you instead mount the current working directory as `/mnt` where docker starts shellcheck, the paths will be the same so glob expansion will work:

    docker run -v "$PWD:/mnt" koalaman/shellcheck *.sh

The docs have been updated in d943ef6. Let me know if there's any issues with this approach.

**Comment by client9** [comment]
Hi @koalaman that's great.  thanks.
