### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by Lynn-Page** [koalaman/shellcheck#940]
#!/your/interpreter
your script here
if [ ! id -u 2> /dev/null -eq 0 ]; then
  echo "error: this script must be run as root"
  exit 1
fi
```

#### Here's what shellcheck currently says:
^-- SC1009: The mentioned parser error was in this if expression.
   ^-- SC1073: Couldn't parse this test expression.
               ^-- SC1072: Fix any mentioned problems and try again.


#### Here's what I wanted or expected to see:
no syntax issues!

**Comment by Nightfirecat** [comment]
I believe it's because that is improper formatting of a conditional... In bash, I find that both of the following commands will not pass the conditional: (nothing is printed to stdout here)

```
if [ ! id -u 2> /dev/null -eq 0 ]; then
  echo 'true'
fi
if [ id -u 2> /dev/null -eq 0 ]; then
  echo 'true'
fi
```

That said, the following passes Shellcheck validation without warning and works correctly:

```
#!/bin/bash
if [ ! "$(id -u 2> /dev/null)" -eq 0 ]; then
  echo "error: this script must be run as root"
  exit 1
fi
```

**Comment by koalaman** [comment]
This is invalid syntax in both bash and ShellCheck.

In bash, the error message you get is squashed due to the `2> /dev/null` that applies to `[` and not `id`: 

```
$ [ ! id -u -eq 0 ]
bash: [: too many arguments
```

Fortunately ShellCheck is not so easily fooled :P

You can use `$(id -u)` like @Nightfirecat suggests. Since `id -u` shouldn't be giving errors in the first place, you can leave stderr and just use `[ "$(id -u)" -ne 0 ]` to avoid hiding any other relevant errors.

**Comment by kurahaupo** [comment]
Is there any version of Bash for which this wouldn't suffice:

```
    die() { printf '%s\n' "$*"; exit 1;}
    ((EUID == 0)) || die "This script must be run as root"
```
