### ISSUE TITLE
Bad syntax recommendation

### ISSUE THREAD

**Issue by mcandre** [koalaman/shellcheck#978]
When ShellCheck scans the content `:() { : | : &; }`, ShellCheck mistakenly reports that the code should be simplified to `:() { : | : & }` without the semicolon. However, this is actually invalid for single line function declarations.

**Comment by koalaman** [comment]
My bash 4.4.12 accepts the latter but not the former. How are you testing this?

**Comment by mcandre** [comment]
Not all systems use bash 4.4.12. I tested this by sending the snippets to bash inside a Docker container, for a relatively easy way to shutdown the ensuing forkbombs when the syntax is accepted.

**Comment by koalaman** [comment]
Which version does your docker image use? `&;` is a syntax error on all versions I'm aware of.

**Comment by kurahaupo** [comment]
Hi Andrew

*How* are you sending it inside the Docker container?

As Koalaman says, &; is forbidden by most shells, so this is very strange.

You won't get a forkbomb unless and until you call the function; simply
defining it is safe. Or change the name of the function so that it's not
recursive, like

    ::() { : | : & }
    ::() { : | : &; }

Commands can be terminated by newlines, semicolons, and ampersands.
Additional newlines are permitted in some places, but other command
terminators are not permitted on empty commands.

So I suspect there's a fault in your testing methodology somewhere.

-Martin

**Comment by mcandre** [comment]
A semicolon is required for POSIX-style shell scripts that express a code block, such as a function declaration, as a single line. See https://askubuntu.com/questions/521937/write-function-in-one-line-into-bashrc

**Comment by Pawamoy** [comment]
From bash manual:

> A list is a sequence of one or more pipelines separated by one of the  operators  ;,  &,
       &&, or ||, and optionally terminated by one of ;, &, or <newline>.

> If  a command is terminated by the control operator &, the shell executes the command in
       the background in a subshell.  The shell does not wait for the command  to  finish,  and
       the  return status is 0.  Commands separated by a ; are executed sequentially; the shell
       waits for each command to terminate in turn.  The return status is the  exit  status  of
       the last command executed.

These paragraphs implicitly say that a command is either terminated by `&` or `;`, not both.
Also, when trying in `sh`:

```
$ f() { : | : &; }                                             
sh: 1: Syntax error: ";" unexpected
```
